### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by pdellepiane** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#10]
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'An uploaded file must be an array or an instance of UploadedFile.' in C:\xampp\htdocs\laravel5startersite\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\FileBag.php:59 Stack trace: #0 C:\xampp\htdocs\laravel5startersite\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\FileBag.php(73): Symfony\Component\HttpFoundation\FileBag->set('files', NULL) #1 C:\xampp\htdocs\laravel5startersite\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\FileBag.php(48): Symfony\Component\HttpFoundation\FileBag->add(Array) #2 C:\xampp\htdocs\laravel5startersite\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\FileBag.php(37): Symfony\Component\HttpFoundation\FileBag->replace(Array) #3 C:\xampp\htdocs\laravel5startersite\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Request.php(448): Symfony\Component\HttpFoundation\FileBag->__construct(Array) #4 C:\xampp\htdocs\laravel5startersite\vendor\laravel in C:\xampp\htdocs\laravel5startersite\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\FileBag.php on line 59
![image](https://cloud.githubusercontent.com/assets/6115355/4966043/36ef08ee-67a9-11e4-9440-04f12b18ab5b.png)

**Comment by stojankukrika** [comment]
It's now works and it fixed after migrate to L5. TnX for comment :+1:
