### ISSUE TITLE
nginx config

### ISSUE THREAD

**Issue by LarryEitel** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#100]
Everything installed and spun up great except one thing... article image links are broken. 

Can someone please share their nginx configuration for a domain hosting this Starter-Site?

Thank You :)

Here's what I have at the moment.

    
    server {

        listen   80;

        root /srv/www/of/lv5/public;
        index index.php index.html index.htm;

        server_name of.com;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        access_log off;

        access_log  /var/log/nginx/of.access.log;
        error_log  /var/log/nginx/of.error.log;
        rewrite_log on;

        sendfile off;

        location ~* \.php$ {
            try_files $uri /index.php =404;

            # fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/var/run/php5-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /srv/www/of/lv5/public/$fastcgi_script_name;
            include fastcgi_params;
        }

        location ~ /\.ht {
            deny all;
        }

        location ~* ^/(css|img|images|js|flv|swf|download)/(.+)$ {
          root /srv/www/of/lv5/public;
        }

    }

**Comment by phpclub** [comment]
location        ~*      ^.+.(jpg|jpeg|gif|ico|js|png)$
        {
         root                   /srv/www/;
                        access_log              off;
                    expires                 7d;
}

**Comment by LarryEitel** [comment]
I may the change. This is an image link that is invalid:

`http://of.com/appfiles/photoalbum//thumbs//home/vagrant/Code/of/lv5/public/appfiles/photoalbum/6ea59f8b95757bc9174cc8584b720d97.jpg`

**Comment by LarryEitel** [comment]
After some piddling and comparing other nginx sites it have running, the following is working for direct links to images. However, photo albums and video thumbnails are still not working.

server {

        listen   80;

        server_name of.com;

        set $doc_root '/of/lv5/public';
        set $home_path "$doc_root/cpo/public";

        index index.php index.html index.htm;
        charset utf-8;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        access_log off;


        access_log  /var/log/nginx/of.access.log;
        error_log  /var/log/nginx/of.error.log;
        rewrite_log on;

        ; sendfile off;


        location ~ /\.ht {
            deny all;
        }

        location / {
          try_files $uri $uri/ /index.php$is_args$args;
        }

        # pass the PHP scripts to FastCGI server listening on /var/run/php5-fpm.sock
        location ~ \.php$ {
          try_files $uri /index.php =404;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
        }

        location ~* ^/(css|img|images|js|flv|swf|download)/(.+)$ {
          root $home_path;
            access_log off;
            expires 7d;
        }
    }

**Comment by kezkankrayon** [comment]
Currently the database seed (tests/factories/factory.php) doesn't put files in the correct directories or populate the database correctly. Pull request 9f448ae addresses this issue.
