### ISSUE TITLE
i cant login with admin@admin.com from the demo 

### ISSUE THREAD

**Issue by gabak** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#106]
i cant login with admin@admin.com from the demo and when during the installation process i got error in the folder: bootstrap/vendor/autoload.php in line 17. what can i do pls help

**Comment by prashantidealittechno** [comment]
Check the step 4, did you create the .env file as explained below and edit the file with your database. database username and database password?
------------------------
<a name="step4"></a>
### Step 4: Create database

If you finished first three steps, now you can create database on your database server(MySQL). You must create database
with utf-8 collation(uft8_general_ci), to install and application work perfectly.
After that, copy .env.example and rename it as .env and put connection and change default database connection name, only database connection, put name database, database username and password.

**Comment by gabak** [comment]
thanks, i ve done that now but i can not run gulp from command line, it say can not find laravel-elixir module cos i can not install the bootstrap css and i cant enter dashboard. thanks

**Comment by stojankukrika** [comment]
you need install nodejs to. Please read a instruction in readme file.
