### ISSUE TITLE
error after composer install

### ISSUE THREAD

**Issue by cladon** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#107]
after the command composer install i get the next error

" syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING)"

What do i have to do to solve this error

**Comment by stojankukrika** [comment]
You need to install php 5.5 or newer, laravel 5 req. php 5.5.x or newer

**Comment by cladon** [comment]
I have installed the last release of xampp and composer and i still get the same error

![error](https://cloud.githubusercontent.com/assets/3923811/7991238/01d71ace-0af7-11e5-90f1-aa76b9d03b97.PNG)

**Comment by stojankukrika** [comment]
Try delete vendor directory and try again composer install.
