### ISSUE TITLE
error after composer install 2

### ISSUE THREAD

**Issue by cladon** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#108]
I have installed the last release of xampp and composer and i still get the same error

![error](https://cloud.githubusercontent.com/assets/3923811/7991238/01d71ace-0af7-11e5-90f1-aa76b9d03b97.PNG)

**Comment by stojankukrika** [comment]
Try delete vendor directory and try again composer install.

**Comment by cladon** [comment]
I have deleted vendor and tried again composer install. I have to create a gitHub oAuth token to get over the API rate?

![error2](https://cloud.githubusercontent.com/assets/3923811/7991885/ccc70ae2-0afb-11e5-9060-16bee9155b86.PNG)

Where can I do this?

**Comment by stojankukrika** [comment]
I never get this error. Maybe laravel or other package change. I do not know where is problem, but I try to fix it soon.

**Comment by cladon** [comment]
I will come back later this evening. I am from Belgium and the time is 21:02.

**Comment by cladon** [comment]
I was abel to regeneratie the github oAuth token. I have deleted  the directory "vendor" and tried again composer install.

I get these lines

D:\xampp\htdocs\Dev\Syntra\BE2\Laravel-5-Bootstrap-3-Starter-Site-master>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing symfony/finder (v2.6.9)
    Loading from cache

  - Installing symfony/var-dumper (v2.6.9)
    Loading from cache

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing maximebf/debugbar (v1.10.4)
    Loading from cache

  - Installing vlucas/phpdotenv (v1.1.1)
    Loading from cache

  - Installing symfony/translation (v2.6.9)
    Loading from cache

  - Installing symfony/security-core (v2.6.9)
    Loading from cache

  - Installing symfony/routing (v2.6.9)
    Loading from cache

  - Installing symfony/process (v2.6.9)
    Loading from cache

  - Installing symfony/http-foundation (v2.6.9)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.7.0)
    Loading from cache

  - Installing symfony/debug (v2.6.9)
    Loading from cache

  - Installing symfony/http-kernel (v2.6.9)
    Loading from cache

  - Installing symfony/console (v2.6.9)
    Loading from cache

  - Installing swiftmailer/swiftmailer (v5.4.0)
    Loading from cache

  - Installing nikic/php-parser (v1.3.0)
    Loading from cache

  - Installing jakub-onderka/php-console-color (0.1)
    Loading from cache

  - Installing jakub-onderka/php-console-highlighter (v0.3.1)
    Loading from cache

  - Installing dnoegel/php-xdg-base-dir (0.1)
    Loading from cache

  - Installing psy/psysh (v0.4.4)
    Loading from cache

  - Installing nesbot/carbon (1.19.0)
    Loading from cache

  - Installing mtdowling/cron-expression (v1.0.4)
    Loading from cache

  - Installing monolog/monolog (1.13.1)
    Loading from cache

  - Installing league/flysystem (1.0.3)
    Loading from cache

  - Installing jeremeamia/superclosure (2.1.0)
    Loading from cache

  - Installing ircmaxell/password-compat (v1.0.4)
    Loading from cache

  - Installing doctrine/inflector (v1.0.1)
    Loading from cache

  - Installing danielstjules/stringy (1.9.0)
    Loading from cache

  - Installing symfony/filesystem (v2.7.0)
    Loading from cache

  - Installing classpreloader/classpreloader (1.4.0)
    Loading from cache

  - Installing laravel/framework (v5.0.32)
    Loading from cache

  - Installing barryvdh/laravel-debugbar (v2.0.3)
    Loading from cache

  - Installing doctrine/lexer (v1.0.1)
    Loading from cache

  - Installing doctrine/annotations (v1.2.4)
    Loading from cache

  - Installing doctrine/cache (v1.4.1)
    Loading from cache

  - Installing doctrine/collections (v1.3.0)
    Loading from cache

  - Installing doctrine/common (v2.5.0)
    Loading from cache

  - Installing doctrine/dbal (v2.5.1)
    Loading from cache

  - Installing illuminate/html (v5.0.0)
    Loading from cache

  - Installing intervention/image (2.2.0)
    Loading from cache

  - Installing laracasts/flash (1.3.3)
    Loading from cache

  - Installing fzaninotto/faker (v1.5.0)
    Loading from cache

  - Installing laracasts/testdummy (2.3.2)
    Loading from cache

  - Installing yajra/laravel-datatables-oracle (v5.2.2)
    Loading from cache

  - Installing laracasts/generators (1.1.1)
    Loading from cache

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Loading from cache

  - Installing symfony/yaml (v2.7.0)
    Loading from cache

  - Installing sebastian/recursion-context (1.0.0)
    Loading from cache

  - Installing sebastian/exporter (1.2.0)
    Loading from cache

  - Installing sebastian/diff (1.3.0)
    Loading from cache

  - Installing sebastian/comparator (1.1.1)
    Loading from cache

  - Installing doctrine/instantiator (1.0.4)
    Loading from cache

  - Installing phpspec/prophecy (v1.4.1)
    Loading from cache

  - Installing phpspec/php-diff (v1.0.2)
    Loading from cache

  - Installing phpspec/phpspec (2.2.1)
    Loading from cache

  - Installing phpunit/php-token-stream (1.4.1)
    Loading from cache

  - Installing sebastian/version (1.0.5)
    Loading from cache

  - Installing sebastian/global-state (1.0.0)
    Loading from cache

  - Installing sebastian/environment (1.2.2)
    Loading from cache

  - Installing phpunit/php-text-template (1.2.0)
    Loading from cache

  - Installing phpunit/phpunit-mock-objects (2.3.3)
    Loading from cache

  - Installing phpunit/php-timer (1.0.5)
    Loading from cache

  - Installing phpunit/php-file-iterator (1.4.0)
    Loading from cache

  - Installing phpunit/php-code-coverage (2.1.3)
    Loading from cache

  - Installing phpunit/phpunit (4.6.10)
    Loading from cache

symfony/var-dumper suggests installing ext-symfony_debug ()
maximebf/debugbar suggests installing kriswallsmith/assetic (The best way to manage assets)
maximebf/debugbar suggests installing predis/predis (Redis storage)
symfony/translation suggests installing symfony/config ()
symfony/security-core suggests installing symfony/expression-language (For using the expression voter)
symfony/security-core suggests installing symfony/validator (For using the user password constraint)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/class-loader ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
psy/psysh suggests installing ext-pcntl (Enabling the PCNTL extension makes PsySH a lot happier :))
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing ext-posix (If you have PCNTL, you'll want the POSIX extension as well.)
psy/psysh suggests installing ext-readline (Enables support for arrow-key history navigation, and showing and manipulating command history.)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing videlalvaro/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-copy (Allows you to use Copy.com storage)
league/flysystem suggests installing league/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
league/flysystem suggests installing predis/predis (Allows you to use Predis for caching)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (~2.4).)
laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun and Mandrill mail drivers (~5.0).)
laravel/framework suggests installing iron-io/iron_mq (Required to use the iron queue driver (~1.5).)
laravel/framework suggests installing league/flysystem-aws-s3-v2 (Required to use the Flysystem S3 driver (~1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
fzaninotto/faker suggests installing ext-intl (*)
yajra/laravel-datatables-oracle suggests installing league/fractal (Can be use to transform DataTables output in a proper API format)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
phpspec/phpspec suggests installing phpspec/nyan-formatters (~1.0 ÔÇô Adds Nyan formatters)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Generating autoload files



  [Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING)



Script php artisan clear-compiled handling the post-install-cmd event returned with an error



  [RuntimeException]
  Error Output:

**Comment by sineld** [comment]
change

	"scripts": {
		"post-update-cmd": [
          "php artisan clear-compiled",
          "php artisan optimize"
		]
	},

to

	"scripts": {
		"post-update-cmd": [
		]
	},

This may solve this issue.

**Comment by cladon** [comment]
I have done the changes in composer.json and I have done the same steps as in the previous commit.

I get the same errors

**Comment by cladon** [comment]
Is there a bug in the file FatalErrorException.php?


 [Symfony\Component\Debug\Exception\FatalErrorException]
 syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING)

**Comment by cladon** [comment]
It was a problem with a difficult uninstall of Xampp.

It is working fine at this moment!!

**Comment by stojankukrika** [comment]
How did you fix the problem? Because I didn't make that situation and works well in my xampp on may local computer.

**Comment by cladon** [comment]
I have a Laptop and a desktop computer. On my laptop is worked perfect. On my desktop it didn't work. On both computers i use xampp.

THe version of PHP on my laptop >5,5 on my desktop < 5,5. 

Before a new install of xampp i did a uninstall of the program. The folder xampp was not deleted. In was unpossible to deleted it. 

I did a new install of xampp on a different partition of my harddisk. It was working perfect but php was not > 5,5. Strange!!!

I dit againe a uninstall of xampp. And deleted the remaining folder on my disk with the program "unlocker". Now i was able to delete tho whole folder xampp.

I did again a new install of xampp.

I followed the steps in you manual and now it is working perfect.

THe only problem i have now at this moment is how to restore my database into the folder d:\xampp\mysql\data without problems. When i restore al the databases and files I haven't access to myphpadmin .... 

That is a problem for the futher ...

**Comment by stojankukrika** [comment]
Hm... Strange!

**Comment by stojankukrika** [comment]
Hm... Strange!

For new problem.I have a same problem when I install a xampp. Well, then I try only copy mysql\data files, and mysql shows me a databases, and tables in left side but I can't access to any database table and some table is missing. So I must install MySQL Workbench and find a way to start old xampp and backup all database into one dump file, and then restore it in new xampp and everything is works.I think that mysql lose access rights in that copying files so that may be a problem, but with backup everything works perfect.

**Comment by cladon** [comment]
Do you only copy the data files? I copied the whole folder but. The result is that i haven't access to mysql.

**Comment by stojankukrika** [comment]
Yea I copyed all files from data folder from one server to other,but I cann't access to my tables on any database.But helps backup databases and restore to new version of server.

**Comment by cladon** [comment]
Hello Stojan 

In the file index.blade.php (... \resources\views\admin\users\index.blade.php? you are using 
{{ trans( "admin/modal.new" ) } 

Can you explaine what is does. I can not find any info about it. 

Greetings 

Donald 

----- Oorspronkelijk bericht -----

Van: "Stojan Kukrika" <notifications@github.com> 
Aan: "mrakodol/Laravel-5-Bootstrap-3-Starter-Site" <Laravel-5-Bootstrap-3-Starter-Site@noreply.github.com> 
Cc: "donald claessens" <donald.claessens@telenet.be> 
Verzonden: Zaterdag 6 juni 2015 16:00:59 
Onderwerp: Re: [Laravel-5-Bootstrap-3-Starter-Site] error after composer install 2 (#108) 



Yea I copyed all files from data folder from one server to other,but I cann't access to my tables on any database.But helps backup databases and restore to new version of server.

**Comment by stojankukrika** [comment]
Trans method is overlaped language class that translate text in selected language.Please read i laravel docs about multilanguages.
Greetings

**Comment by manshu** [comment]
that should be solved with composer require predis/predis
