### ISSUE TITLE
Admin Datatable show an error

### ISSUE THREAD

**Issue by vafrcor** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#109]
At these page:
* /admin/news
* /admin/video
* /admin/photo

jQuery Datatable show alert error:
![admin-datatables-error-news-photo-video-search](https://cloud.githubusercontent.com/assets/2148366/8100908/c8954688-103b-11e5-9c21-75525f8172b6.jpg)

For example Photo Album Query show an error as below:
```sql
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'albumid' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as row_count from `videos` inner join `languages` on `languages`.`id` = `videos`.`language_id` inner join `video_albums` on `video_albums`.`id` = `videos`.`video_album_id` where `videos`.`video_album_id` > 0 and (LOWER(`videos`.`id`) LIKE %2% or LOWER(`albumid`) LIKE %2% or LOWER(`videos`.`name`) LIKE %2% or LOWER(`category`) LIKE %2% or LOWER(`videos`.`album_cover`) LIKE %2% or LOWER(`language`) LIKE %2%) order by `videos`.`position` asc) count_row_table)
```
thank you for any response

**Comment by stojankukrika** [comment]
When did you get a version?Because it's old error what I fixed.Try download a new version.

**Comment by roryza** [comment]
I ran into similar error a previous time with, then I saw you fixed it Stojan so I pulled and updated and all was well, and then I updated with composer recently and noticed this issue last night so it seems like it's back, or something very similar is back.

**Comment by vafrcor** [comment]
@stojankukrika : thank you for reply, i will check the update. my project use L5 starter kit from this date ==> May 20, 2015.

**Comment by stojankukrika** [comment]
try now, I am update it to laravel 5.1, maybe it's solve that problem.

**Comment by kezkankrayon** [comment]
@stojankukrika have you seen http://www.jquery-bootgrid.com/Examples? I reckon it would be a good replacement for DataTables.

**Comment by stojankukrika** [comment]
No @kezkankrayon I didn't see that before. It's look pretty cool, but for now and in this project I prefer this DataTables.
