### ISSUE TITLE
Allow username or email address login

### ISSUE THREAD

**Issue by sseshachala** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#110]
How can I allow user to login using email or username?

On another note, I am looking to migrate 4.2 to 5.0. How big of a deal is it?
In 4.2, I have used confide for login/register and hybridauth for social login.

**Comment by stojankukrika** [comment]
You can change in AuthenticatesAndRegistersUsers postLogin method to use email or username to login user.

For migrate project from 4.2 to 5.0 read this http://laravel.com/docs/5.1/upgrade step by step. You need to change controllers and models and other change a place, because other is the same :) You need a few hours(depends to size of project) to migrate everything.

**Comment by sseshachala** [comment]
Thanks. Like this? can you please let me know? how do we change this method?

/**
	 * Handle a login request to the application.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function postLogin(Request $request)
	{
		$this->validate($request, [ 'username' => 'required',
			'email' => 'required|email', 'password' => 'required',
		]);

		$credentials = $request->only('email|username', 'password');

		if ($this->auth->attempt($credentials, $request->has('remember')))
		{
			return redirect()->intended($this->redirectPath());
		}

		return redirect($this->loginPath())
					->withInput($request->only('email|username', 'remember'))
					->withErrors([
						'email' => $this->getFailedLoginMessage(),
					]);
	}

**Comment by stojankukrika** [comment]
Not really. In your code you required username and email with password. You can change this $this->validate($request, ['email' => 'required', 'password' => 'required', 
and then in controller maybe use something like this:
$credentials1 = $request->only('email', 'password'); 
$credentials2 = array('username'=>$request['email'], 'password'=>$request['password']); 
if ($this->auth->attempt($credentials, $request->has('remember')) || $this->auth->attempt($credentials2, $request->has('remember')))
    {
        return redirect()->intended($this->redirectPath());
    }

Try this, maybe it's works :)

**Comment by sseshachala** [comment]
After modifying... do i need to compile or something?

**Comment by stojankukrika** [comment]
No you do not.It's PHP.Learn something about php and then learn some framework.

**Comment by sseshachala** [comment]
No, I understand php. It is just that - I read some where while setting up that we needed to compile, any ways, the code I modified, but the UI still  throws validation error that it needs an email with '@'.

Thanks for the help

**Comment by stojankukrika** [comment]
server will compile your code in every request, every refresh or go to other page.
