### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by spiderbees** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#111]
Dear SIr
i got this error during installtion and i donow know the reason?
could you tell me ?

the error is \

**Comment by spiderbees** [comment]
C:\xampp\htdocs\spider>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for intervention/image 2.2.0 -> satisfiable by interv
ention/image[2.2.0].
    - intervention/image 2.2.0 requires ext-fileinfo * -> the requested PHP exte
nsion fileinfo is missing from your system.

**Comment by DeeJaVu** [comment]
cant you read ????????????????????????

intervention/image 2.2.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.

https://community.xibo.org.uk/t/how-do-i-enable-fileinfo-in-php/78

**Comment by stojankukrika** [comment]
ye, you need to uncomment this line "extension=php_fileinfo.dll" in php.info file
