### ISSUE TITLE
php artisan db:seed

### ISSUE THREAD

**Issue by classical** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#112]
When i run step: php artisan db:seed
it show error:

Seeded: UsersTableSeeder
Seeded: LanguagesTableSeeder
Seeded: ArticleCategoriesTableSeeder
Seeded: ArticlesTableSeeder
Seeded: PhotoAlbumsTableSeeder

                              
  [ErrorException]            
  Undefined index: extension  

[2015-06-16 08:11:51] local.ERROR: exception 'ErrorException' with message 'Undefined index: extension' in /var/www/laravel5/tests/factories/factory.php:47

Other case: i can't pass this line in index.php file:
$response = $kernel->handle(
	$request = Illuminate\Http\Request::capture()
);

Please tell me how to fix it.
Thank you!

PS: i had checked and it working on Window 8.1
This issue happen when install on Ubuntu

**Comment by stojankukrika** [comment]
try now, I am update it to laravel 5.1, maybe it's solve that problem.

**Comment by stojankukrika** [comment]
Now it's fixed
