### ISSUE TITLE
Requirements could not be resolved 

### ISSUE THREAD

**Issue by schettino** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#114]
Hi, 

There's something bad happening when running composer install,

C:\xampp\htdocs\tvopen>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for intervention/image 2.2.0 -> satisfiable by interv
ention/image[2.2.0].
    - intervention/image 2.2.0 requires ext-fileinfo * -> the requested PHP exte
nsion fileinfo is missing from your system.

I did not change a thing after downloading the project. Just got it and tried to install. 

Is it happening with someone else? How can I fix it?

Great project btw,
Thanks!

**Comment by stojankukrika** [comment]
all you need to uncomment this line "extension=php_fileinfo.dll" in php.info file it's same problem like issue #111

**Comment by schettino** [comment]
Ok, now it installing! 

Thank you!

**Comment by stojankukrika** [comment]
You're welcome ;)
