### ISSUE TITLE
Blanc Page

### ISSUE THREAD

**Issue by BenJule** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#120]
I have installed Laravel 5 and configure this correctly but i get an blanc Page! Anyone Idea?

**Comment by stojankukrika** [comment]
Can you add here a Print Screen?

**Comment by BenJule** [comment]
my Apache Error Log: http://paste.debian.net/hidden/3c92dc10/

**Comment by stojankukrika** [comment]
I never seen something like that

**Comment by BenJule** [comment]
php Print Screen is only aviable with Windows, correct? im using Debian :/

**Comment by kezkankrayon** [comment]
@BenJule I think you've got a permission error. What permissions do you have set on `/var/www/html/Laravel-5-Bootstrap-3-Starter-Site-master/storage/logs/`?

**Comment by Mevrael** [comment]
`php artisan cache:clear`
`chmod -R 777 app/storage`
`php artisan dump-autoload`
