### ISSUE TITLE
Task 'default' is not in your gulpfile

### ISSUE THREAD

**Issue by metrey** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#122]
laravel5-starter\gulpfile.js

Task 'default' is not in your gulpfile
Please check the documentation for proper gulpfile formatting

**Comment by metrey** [comment]
Seem the fix is:

    gulp.task('bower', function() {
        return bower();
    });

to 

    gulp.task('default', function() {
       return bower();
   });

**Comment by metrey** [comment]
I think we can place as also this:

    gulp.task('bower', function() {
    	return bower();
    });
    
    gulp.task('default', ['bower']);

But when I run: gulp command I don't find the generated file from sass: 

	'css/site.css',
	'css/admin.css',
	'js/site.js',
	'js/admin.js'

What should be the issue?

**Comment by stojankukrika** [comment]
with task bower works well.
