### ISSUE TITLE
Step 2 composer install

### ISSUE THREAD

**Issue by ferbj** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#123]
im following the steps and on the next steep 2 i had the error on console cmd  composer install into the folder proyect. 
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.jso
n. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for intervention/image 2.2.0 -> satisfiable by interv
ention/image[2.2.0].
    - intervention/image 2.2.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.

exist a solution for this problem?.. thanks for help.

**Comment by Mevrael** [comment]
Enable fileinfo PHP extension
Run "composer update"

**Comment by ferbj** [comment]
thank you.. now works.
