### ISSUE TITLE
css, js file not load in front and backend.

### ISSUE THREAD

**Issue by triminh** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#124]
When i run site in localhost: page response html with no js, css.
![lar-er](https://cloud.githubusercontent.com/assets/6907925/8391232/1af79e98-1ce5-11e5-834c-db111efd148b.png)

**Comment by Mevrael** [comment]
run "php artisan vendor:publish"

http://laravel.com/docs/5.1/packages#public-assets

**Comment by kezkankrayon** [comment]
Run `gulp` to build public assets.

**Comment by stojankukrika** [comment]
:+1: @kezkankrayon

**Comment by triminh** [comment]
I have follow steps, but still the same. When i ran: "npm install" error appear: npm warn  optional dep failed.
