### ISSUE TITLE
Problems to run the application

### ISSUE THREAD

**Issue by Sajib32** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#125]
After installing all the things, it shows this error:

production.ERROR: exception 'InvalidArgumentException' with message 'File css/site.css not defined in asset manifest.' in H:\xampp\htdocs\laravel5starter\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php:681

pls help..

**Comment by stojankukrika** [comment]
Are you read and folow readme?

**Comment by Sajib32** [comment]
yes, sorry to tell that when i run "node -v" and "npm install" it shows that npm is not recognized as an internal and external command..how to install npm in laravel5 with windows cmd. pls help.

**Comment by stojankukrika** [comment]
you need to install nodejs on your computer. Node js instalation you can find here https://nodejs.org/
