### ISSUE TITLE
Loading site for the first time:  Column not found: 1054 Unknown column 'video_albums.deleted_at'

### ISSUE THREAD

**Issue by danielfarina** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#126]
Hello Guys, 

I just installed homestead and followed all instructions. I'm connecting to the database, the tables were migrated and I also installed the sample data. I checked mysql and everything is there. The video tables are empy.  I'm getting the following error. I'm unable to test the page at all. 

QueryException in Connection.php line 629:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'video_albums.deleted_at' in 'where clause' (SQL: select `video_albums`.`id`, `video_albums`.`name`, `video_albums`.`description`, `video_albums`.`folder_id`, (select youtube from videos WHERE album_cover=TRUE and videos.video_album_id=video_albums.id LIMIT 1) AS album_image, (select youtube from videos WHERE videos.video_album_id=video_albums.id ORDER BY position ASC, id ASC LIMIT 1) AS album_image_first from `video_albums` where `video_albums`.`deleted_at` is null limit 8).

**Comment by stojankukrika** [comment]
Sorry for that. I forgot something in videos data table. Please download new migration file and delete tables in your test database and start again migration and seed.Sorry for that.

**Comment by danielfarina** [comment]
Thanks for the quick response!

Dan
