### ISSUE TITLE
npm install Issues. 

### ISSUE THREAD

**Issue by danielfarina** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#127]
Hello Guys, 

I have been trying to get this running for two days now. I'm almost there. I'm running installing Laravel-5-Bootstrap-3-Starter-Site inside a  Laravel Homestead setup. I know it has not been tested yet. I'm planning to make a setup by step tutorial because I ran into several issues. 

So far I got everything inside homestead, the database is working fine, composer worked fine.

I have problems with STEP 5:
npm install

I get a bunch of errors and I tried everything to solve it. 

vagrant@homestead:~/Code/Laravel$ sudo npm install
npm WARN optional dep failed, continuing fsevents@0.3.6
npm ERR! tar.unpack untar error /home/vagrant/.npm/readable-stream/2.0.1/package
.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/source-map/0.3.0/package.tgz
npm WARN optional dep failed, continuing source-map@0.1.43
npm WARN optional dep failed, continuing request@2.58.0
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.37
npm ERR! npm  v2.12.0
npm ERR! path /home/vagrant/Code/Laravel/node_modules/gulp/node_modules/gulp-uti
l/node_modules/dateformat/node_modules/meow/node_modules/indent-string/node_modu
les/repeating/node_modules/is-finite/node_modules/number-is-nan/package.json.408
3a6d121d00f298b23e19fb12b71e4
npm ERR! code EPERM
npm ERR! errno 50

npm ERR! Error: EPERM, open '/home/vagrant/Code/Laravel/node_modules/gulp/node_m
odules/gulp-util/node_modules/dateformat/node_modules/meow/node_modules/indent-s
tring/node_modules/repeating/node_modules/is-finite/node_modules/number-is-nan/p
ackage.json.4083a6d121d00f298b23e19fb12b71e4'
npm ERR!  { [Error: EPERM, open '/home/vagrant/Code/Laravel/node_modules/gulp/no
de_modules/gulp-util/node_modules/dateformat/node_modules/meow/node_modules/inde
nt-string/node_modules/repeating/node_modules/is-finite/node_modules/number-is-n
an/package.json.4083a6d121d00f298b23e19fb12b71e4']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: '/home/vagrant/Code/Laravel/node_modules/gulp/node_modules/gulp
-util/node_modules/dateformat/node_modules/meow/node_modules/indent-string/node_
modules/repeating/node_modules/is-finite/node_modules/number-is-nan/package.json
.4083a6d121d00f298b23e19fb12b71e4' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.37
npm ERR! npm  v2.12.0
npm ERR! path npm-debug.log.5178fbb13e1b0faf7448565546fb6da5
npm ERR! code ETXTBSY
npm ERR! errno 62

npm ERR! ETXTBSY, rename 'npm-debug.log.5178fbb13e1b0faf7448565546fb6da5'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/Laravel/npm-debug.log

Any suggestions are appreciated.

**Comment by metrey** [comment]
I think I faced that as well after I used the last dev. one, I seem face same issue but didn't remember the steps to solve, likely I tried for each install:

    npm install -g gulp
    npm install -g gulp-bower
    npm install -g gulp-notify
    npm install

**Comment by rafaelqm** [comment]
And if you are using Windows with Vagrant and VirtualBox, install the Node, and gulp at Windows, not at your VM.

**Comment by stojankukrika** [comment]
Try to install new version of nodejs, because I do it now and works so well.
