### ISSUE TITLE
css js missed

### ISSUE THREAD

**Issue by alejandri** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#128]
I followed all steps without errors but appears css and some js missed.
Any idea please...

![sin-titulo-1](https://cloud.githubusercontent.com/assets/3764626/8433803/4fb7a02a-1f1e-11e5-8a13-ac7d0c1fd227.jpg)

**Comment by stojankukrika** [comment]
you need execute a "gulp" command to make js and css file
