### ISSUE TITLE
undefined variable bootstrap sass assets helper in bootswatch yeti _variables.scss

### ISSUE THREAD

**Issue by venkisoft8** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#131]
undefined variable bootstrap sass assets helper in bootswatch yeti _variables.scss

**Comment by mouradsm** [comment]
same issue here when ran gulp

**Comment by ericp-tfd** [comment]
Same here. 
"Sass Compilation Failed!: resources/vendor/bootswatch/yeti/_variables.scss"
"Undefined variable: "$bootstrap-sass-asset-helper"."

**Comment by mouradsm** [comment]
My error 
gulp-notify: [Laravel Elixir] Sass Compilation Failed!: resources/vendor/bootswatch/yeti/_variables.scss
  79:21  Undefined variable: "$bootstrap-sass-asset-helper".

**Comment by mouradsm** [comment]
digging I found this:

**Comment by ummira** [comment]
same issue after gulp:
 gulp-notify: [Laravel Elixir] Sass Compilation Failed!: resources/vendor/bootswatch/yeti/_variables.scss
  79:21  Undefined variable: "$bootstrap-sass-asset-helper".
{ [Error: resources/vendor/bootswatch/yeti/_variables.scss
  79:21  Undefined variable: "$bootstrap-sass-asset-helper".]
  message: 'resources/vendor/bootswatch/yeti/_variables.scss\n  79:21  Undefined variable: "$bootstrap-sass-asset-helper".',
  column: 21,
  line: 79,
  file: 'resources/vendor/bootswatch/yeti/_variables.scss',
  status: 1,
  messageFormatted: '\u001b[4mresources/vendor/bootswatch/yeti/_variables.scss\u001b[24m\n\u001b[90m  79:21\u001b[39m  Undefined variable: "$bootstrap-sass-asset-helper".',
  name: 'Error',
  stack: 'Error: resources/vendor/bootswatch/yeti/_variables.scss\n  79:21  Undefined variable: "$bootstrap-sass-asset-helper".\n    at options.error (/var/www/testing.com/l5st/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:276:32)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
[14:38:01] gulp-notify: [Error running notifier] Could not send message: not found: notify-send
[14:38:01] gulp-notify: [Laravel Elixir] Sass Compilation Failed!: resources/vendor/bootswatch/yeti/_variables.scss
  79:21  Undefined variable: "$bootstrap-sass-asset-helper".
{ [Error: resources/vendor/bootswatch/yeti/_variables.scss
  79:21  Undefined variable: "$bootstrap-sass-asset-helper".]
  message: 'resources/vendor/bootswatch/yeti/_variables.scss\n  79:21  Undefined variable: "$bootstrap-sass-asset-helper".',
  column: 21,
  line: 79,
  file: 'resources/vendor/bootswatch/yeti/_variables.scss',
  status: 1,
  messageFormatted: '\u001b[4mresources/vendor/bootswatch/yeti/_variables.scss\u001b[24m\n\u001b[90m  79:21\u001b[39m  Undefined variable: "$bootstrap-sass-asset-helper".',
  name: 'Error',
  stack: 'Error: resources/vendor/bootswatch/yeti/_variables.scss\n  79:21  Undefined variable: "$bootstrap-sass-asset-helper".\n    at options.error (/var/www/testing.com/l5st/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:276:32)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
[14:38:01] Finished 'sass' after 403 ms
[14:38:01] Starting 'styles'...
[14:38:01] Merging: resources/vendor/jquery-colorbox/example3/colorbox.css, resources/assets/build/site.css
[14:38:01] Merging: resources/vendor/datatables-bootstrap3-plugin/media/css/datatables-bootstrap3.css, resources/vendor/metisMenu/dist/metisMenu.css, resources/assets/build/admin.css
[14:38:01] File not found: resources/assets/build/site.css
[14:38:01] File not found: resources/assets/build/admin.css
[14:38:01] gulp-notify: [Error running notifier] Could not send message: not found: notify-send


no css was loading...

**Comment by mouradsm** [comment]
Solved by https://github.com/thomaspark/bootswatch/commit/ceefe110c1f64b9ebca41215d02c6e50e45d9e19 ;
Just perform a bower update and be happy =)

**Comment by ummira** [comment]
what do you mean -->Just perform a bower update???

**Comment by mouradsm** [comment]
run "bower update" command in your project directory

**Comment by ummira** [comment]
Il 08/07/2015 18:07, Diego Moura ha scritto:
>
> run "bower update" command in your project directory
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mrakodol/Laravel-5-Bootstrap-3-Starter-Site/issues/131#issuecomment-119637618>.
>
just done it....but nothing was change

**Comment by mouradsm** [comment]
so try manually update the bootswatch version in vendor folder

**Comment by ummira** [comment]
Il 08/07/2015 18:07, Diego Moura ha scritto:
>
> run "bower update" command in your project directory
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mrakodol/Laravel-5-Bootstrap-3-Starter-Site/issues/131#issuecomment-119637618>.
>
[17:13:58] gulp-notify: [Error in notifier] Error in plugin 'gulp-notify'
not found: notify-send

**Comment by ericpaige** [comment]
homestead ssh
bower update
gulp
Done! It's fixed. Thank you.

**Comment by kezkankrayon** [comment]
@ummira gulp-notify error is not relevant to #131

https://github.com/mrakodol/Laravel-5-Bootstrap-3-Starter-Site/blob/970796ced09edd54a28bb26ae60164f00c03ca3e/readme.md#L172
