### ISSUE TITLE
Css,Js not work?

### ISSUE THREAD

**Issue by shankhadevpadam** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#132]
I have install the system successfully and also install the npm and run gulp successfully, also css file is generate in public/build/css/ and js file in public/build/js/ folder all work fine.But  {{ elixir('css/admin.css') }},
{{ elixir('css/site.css') }} generate the path like this link href="/build/css/site-2f1d2fc0.css" rel="stylesheet". And my path where laraval is install is like this http://localhost/laravel-admin/public/admin/dashboard

But still not loading the css and js. What is the problem.[Note i follow all the steps and there is no error occur during install even running gulp also.]

**Comment by alejandri** [comment]
command "gulp", "artisan serve" and run under :8000

**Comment by shankhadevpadam** [comment]
Now its work. Did we need any changes while uploading to the server?

**Comment by stojankukrika** [comment]
No you do not need any changes except database connection string :)
