### ISSUE TITLE
Issue with Views Examples

### ISSUE THREAD

**Issue by bepursuant** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#133]
I noticed that in many of your views, you are using {!! !!}, even for items like $post->title, $author->name, and $post->created_at ... Doesn't this open a pretty big vulnerability, allowing arbitrary html to be echoed like that?

**Comment by stojankukrika** [comment]
Yea, you are right. Thank you very much for that :+1: I appreciate it
