### ISSUE TITLE
composer update 

### ISSUE THREAD

**Issue by roselan** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#135]
```
λ composer update
> php artisan clear-compiled



  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Illuminate\Html\HtmlServiceProvider' not found



Script php artisan clear-compiled handling the pre-update-cmd event returned with an error



  [RuntimeException]
  Error Output:

````

I updated composer, tried to replace illuminate/html by "laravelcollective/html" in composer.json (clear-cache, etc). I'm a bit at loss there  as I'm quite new to laravel (installed on laragon).

**Comment by roselan** [comment]
deleting the lockfile and "composer install" resolved the issue

**Comment by stojankukrika** [comment]
OK.Thanks for share solving the problem. :+1:
