### ISSUE TITLE
Why does admin VideoAlbumController use PhotoAlbumRequest?

### ISSUE THREAD

**Issue by CyberiaResurrection** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#138]
Is this a typo, given that app/Http/Requests/Admin/VideoAlbumRequest.php also exists?

Or should both {foo}AlbumRequests be collapsed to a single request type?

**Comment by stojankukrika** [comment]
Yea @CyberiaResurrection you can marge it in one, if you want so. Here is different because it is a start site, and it uses beginners to learn laravel, and anyone who like to use it for start own project, it's not a final project for someone to use it in some site or sell it :)

**Comment by CyberiaResurrection** [comment]
Ok, thanks.  I was asking because of the apparent inconsistency between VideoAlbumController and PhotoAlbumController.

**Comment by stojankukrika** [comment]
Tnx for comment and you see something like that. But I think that is better divide that thinks because there is lot new laravel users who want learn that framework, is is only reason because code have repetition in some places and same code in requests, controller, model and so on..
