### ISSUE TITLE
Does not load css and JS

### ISSUE THREAD

**Issue by oliveiraped** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#139]
Hi i installed Laravel-5-Bootstrap-3-Starter-Site using the manual on github, and when i do http://localhost/aplication, laravel does not load js and css files, can help me ?

Heres his error page on firebug console

"NetworkError: 404 Not Found - http://localhost/build/css/site-70807537.css"
site-70807537.css
"NetworkError: 404 Not Found - http://localhost/build/js/site-fcbe16fa.js"
site-fcbe16fa.js
"NetworkError: 404 Not Found - http://localhost/aquaria/public/_debugbar/assets/stylesheets?1436453519"
stylesh...6453519
"NetworkError: 404 Not Found - http://localhost/aquaria/public/_debugbar/assets/javascript?1423122680"
javascr...3122680
"NetworkError: 404 Not Found - http://localhost/aquaria/public/_debugbar/assets/stylesheets?1436453519"
stylesh...6453519
"NetworkError: 404 Not Found - http://localhost/aquaria/public/_debugbar/assets/javascript?1423122680"
javascr...3122680
ReferenceError: $ is not defined
/aquaria/public/ (line 161, col 4)
ReferenceError: $ is not defined
/aquaria/public/ (line 167, col 8)
ReferenceError: jQuery is not defined
/aquaria/public/ (line 176)
ReferenceError: PhpDebugBar is not defined
/aquaria/public/ (line 178, col 4)

**Comment by stojankukrika** [comment]
When did you download this start site? Because this morning I fix it.

**Comment by oliveiraped** [comment]
yesterday, i will redeploy agan and try again.

**Comment by oliveiraped** [comment]
It Works Now .
