### ISSUE TITLE
Css and js files are missing

### ISSUE THREAD

**Issue by tanmuhittin** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#140]
Hi I just installed a fresh one by following instructions but css and js files look like missing. I renamed all.js and all.css to site.js and site.css and problem solved

**Comment by stojankukrika** [comment]
I download currently version and follow steps from readme and in final all is works well.

**Comment by marcelotk15** [comment]
I have the same problem, and the solution of @tanmuhittin  work for me too.
