### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by singh7889** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#141]
Warning: require(C:\xampp\htdocs\blog\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in :C\xampp\htdocs\blog\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\blog\bootstrap/../vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\blog\bootstrap\autoload.php on line 17

**Comment by singh7889** [comment]
please solve ...

**Comment by Mevrael** [comment]
composer update
