### ISSUE TITLE
Error when composer install

### ISSUE THREAD

**Issue by singh7889** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#142]
Problem 1-installation request for intervention/image 2.2.0-> satisfiable by intervention/image[2.2.0].
  -intervention/image 2.2.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.

please help .

**Comment by triminh** [comment]
Remove semi-colon at ;extension=php_fileinfo.dll in php.ini file and restart server.

**Comment by stojankukrika** [comment]
please read readme: https://github.com/mrakodol/Laravel-5-Bootstrap-3-Starter-Site#step5
