### ISSUE TITLE
missing flags.css file?

### ISSUE THREAD

**Issue by bernier** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#144]
Hello,
in resources/views/admin/language/index.blade.php you define flags.css
But I don't see it anywhere in the repo.

@section('styles')
    @parent
    <link href="{{ asset("css/flags.css") }}" rel="stylesheet">
@endsection

Thanks

**Comment by stojankukrika** [comment]
Flags css is defined in gulpfile :)
