### ISSUE TITLE
View [emails.password] not found

### ISSUE THREAD

**Issue by alejandri** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#145]
When reset password return this msg. I solved changed up one level the file password.blade.php in resources/views/emails/auth

**Comment by stojankukrika** [comment]
Can you explain to me what is going on?I do not understand you.

**Comment by alejandri** [comment]
Yes, sorry my english. When submit form reset password E-Mail in url 

"http://localhost/mrakodol/public/password/email" 

resources/views/emails/auth/password.blade.php not found.
Solved moving file to 
resources/views/emails/password.blade.php

![sin-titulo-1](https://cloud.githubusercontent.com/assets/3764626/8873657/1703bf4c-31df-11e5-993d-c5102a566125.jpg)

**Comment by stojankukrika** [comment]
Aha, that you think :) I never test that functionality :) OK, I copy it now on emails view folder. TNX bro :+1:
