### ISSUE TITLE
Error when listing languages

### ISSUE THREAD

**Issue by kameleono** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#146]
Hi!

I get this to errors when listing languages:

DataTables warning: table id=table - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

and 

TypeError: $(...).sortable is not a function

Could they be related?

Are this known issues?

**Comment by stojankukrika** [comment]
I hope that now you did not have that problem :)

**Comment by kameleono** [comment]
Hi! thanks for your quickly answer!

I still have the problem..and it is worse because no one listing is working in the dashboard. Did you test it in your installation?

**Comment by stojankukrika** [comment]
:( Yea I text it...But I tray to find where is problem and tray to fix it.

**Comment by kameleono** [comment]
Maybe I'm doing something wrong?

I was testing and I think the problem is here, in Admin / LanguagueController

->edit_column('icon', '{{ ($icon!="")? "<span class=\"flag $icon\" alt=\"flag\">&nbsp</span>":""; }}') 

If I erase the semicolon for this result 

->edit_column('icon', '{{ ($icon!="")? "<span class=\"flag $icon\" alt=\"flag\">&nbsp</span>":"" }}')

It works but the problem is that it prints the html

**Comment by samkitano** [comment]
To fix the data-table error, just replace (in LanguageController.php at line 148)

```php
->edit_column('icon', '{{ ($icon!="")? "<span class=\"flag $icon\" alt=\"flag\">&nbsp</span>":""; }}')
```

with
```php
->edit_column('icon', function($row) {
    return $row->icon != '' ? "<span class=\"flag $row->icon\" alt=\"flag\">&nbsp;</span>":"";
})
```

About the javascript error (TypeError: $(...).sortable is not a function):

It appears that the jQuery UI library is not being included/loaded anywhere on the build.

**Comment by stojankukrika** [comment]
now it's fixed
