### ISSUE TITLE
Dashboard panel jQuery is not defined

### ISSUE THREAD

**Issue by ngiteam** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#147]
Hi,
In admin panel js not working

I get this errors on browser console:
Uncaught ReferenceError: jQuery is not defined - admin.js:40
Uncaught ReferenceError: $ is not defined - bootstrap-dataTables-paging.js:2
Uncaught ReferenceError: $ is not defined - datatables.fnReloadAjax.js:14
Uncaught TypeError: Cannot read property 'fn' of undefined modal.js:198 modal.js:246

Best regards

**Comment by ivanmilosavljevic** [comment]
I have same problem, too.

**Comment by subetha** [comment]
In ressources\views\app.blade.php 
move this line into the head area
```
<script src="{{ asset('js/site.js') }}"></script>
```

jQuery library has to be included before other jQuery plugins are loaded.

**Comment by stojankukrika** [comment]
TNX @subetha I fix it now :) sorry for that error @ivanmilosavljevic & @ngiteam
