### ISSUE TITLE
site.css / site.js dont exist

### ISSUE THREAD

**Issue by aminking2005** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#152]
in app.blade.php there is a link to css/site.css and js/site.js
but these files dont exist
it should be all.css and all.js

and glyficons dont load

**Comment by jryd** [comment]
I am having the same issue

**Comment by jryd** [comment]
@aminking2005 I solved this by renaming all.js and all.css to site.js and site.css.

**Comment by mlourens** [comment]
@jryd best to rename the css files in the blade templates to all.css, all.css 
these contain 'all' js and css for the different pages. /admin/layouts/default.blade.php for example refers still to admin,js and admin.css. This should also be changed to all.css and all.js.

**Comment by stojankukrika** [comment]
yea, sometimes gulp can make this problem. Run gulp again to solve it.
