### ISSUE TITLE
datatables warning

### ISSUE THREAD

**Issue by aminking2005** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#153]
when trying to open languages page a popup error occur 
Datatable warning: table_id = table.....

**Comment by stojankukrika** [comment]
I just post a new version. Can you download a new version and test it?

**Comment by stojankukrika** [comment]
Nobody didn't say that isn't work wrong so I close this issue.

**Comment by Mashpy** [comment]
yes, i am getting the same error =>

DataTables warning: table id=table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by iliyaZelenko** [comment]
I also have an error

**Comment by jpawlowski** [comment]
Using Laravel 5.2, this error still persists.
