### ISSUE TITLE
Missing Css and Js file when using gulp

### ISSUE THREAD

**Issue by Trexology** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#158]
When using gulp.

Fetching Styles Source Files...
   - resources/vendor/datatables-bootstrap3-plugin/media/css/datatables-bootstrap3.css <-- Not Found
   - resources/vendor/metisMenu/dist/metisMenu.css <-- Not Found
   - resources/assets/build/admin.css <-- Not Found

Saving To...
   - public/css/admin.css

[10:37:47] Finished 'styles' after 15 ms
[10:37:47] Starting 'scripts'...

Fetching Scripts Source Files...
   - resources/vendor/datatables/media/js/jquery.dataTables.js <-- Not Found
   - resources/vendor/datatables-bootstrap3-plugin/media/js/datatables-bootstrap3.js <-- Not Found
   - resources/vendor/metisMenu/dist/metisMenu.js <-- Not Found

Saving To...
   - public/js/admin.js

[10:37:47] Finished 'scripts' after 26 ms
[10:37:47] Starting 'version'...

Fetching Version Source Files...
   - public/css/site.css <-- Not Found
   - public/css/admin.css <-- Not Found
   - public/js/site.js <-- Not Found
   - public/js/admin.js <-- Not Found
=============================
Using a mac machines, composer installed successfully. Since i am using a mac, i assume i would not need to uncomment the "php_fileinfo.dll"

It also complain about missing site.css and site.js, but that can be a easy fix by renaming both files.

**Comment by MECU** [comment]
I ran gulp a second time and all the files were generated correctly.

**Comment by stojankukrika** [comment]
yea, sometimes gulp can make this problem. Run gulp again to solve it.
