### ISSUE TITLE
Image Upload Issue

### ISSUE THREAD

**Issue by prakashluitel88** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#159]
I tried to upload making one Menu.
Image upload problem is there.
Also, there is in News menu- Uploading image is not working.

**Comment by stojankukrika** [comment]
OK. I will fix it soon.

**Comment by stojankukrika** [comment]
Yea, I currently work on new version with a loot of fixes

**Comment by stojankukrika** [comment]
I just post a new version. Can you download a new version and test it?

**Comment by stojankukrika** [comment]
Nobody didn't say that isn't work wrong so I close this issue.
