### ISSUE TITLE
Errors durring gulp process on windows

### ISSUE THREAD

**Issue by pierreSLA** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#160]
Durring the setup step 5 i get the following errors (just the errors in comment):
"""
Fetching Copy Source Files...
   - resources/vendor/flag-sprites/dist/css/flag-sprites.min.css <-- Not Found
Fetching Copy Source Files...
   - resources/vendor/flag-sprites/dist/img/flags.png <-- Not Found
[19:49:05] gulp-notify: [Laravel Elixir] Sass Compilation Failed: resources\asse
ts\sass\site.scss
  2:9  file to import not found or unreadable: yeti/variables
Current dir:
{ message: 'resources\\assets\\sass\\site.scss\n  2:9  file to import not found
or unreadable: yeti/variables\nCurrent dir: ',
  column: 9,
  line: 2,
  file: 'stdin',
  status: 1,
  messageFormatted: '\u001b[4mresources\\assets\\sass\\site.scss\u001b[24m\n\u00
1b[90m  2:9\u001b[39m  file to import not found or unreadable: yeti/variables\nC
urrent dir: ',
  name: 'Error',
  stack: 'Error: resources\\assets\\sass\\site.scss\n  2:9  file to import not f
ound or unreadable: yeti/variables\nCurrent dir: \n    at options.error (F:\\xam
pp\\htdocs\\lar-slanator.com\\node_modules\\laravel-elixir\\node_modules\\gulp-s
ass\\node_modules\\node-sass\\lib\\index.js:276:32)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
[19:49:05] Finished 'sass' after 1.09 s
[19:49:05] Starting 'styles'...

Fetching Styles Source Files...
   - resources\vendor\jquery-colorbox\example3\colorbox.css <-- Not Found
   - resources\assets\build\site.css <-- Not Found

Saving To...
   - public/css/site.css

[19:49:05] Finished 'styles' after 16 ms
[19:49:05] Starting 'scripts'...

Fetching Scripts Source Files...
   - resources\vendor\jquery-legacy\dist\jquery.js <-- Not Found
   - resources\vendor\bootstrap-sass\assets\javascripts\bootstrap.js <-- Not Fou
nd
   - resources\vendor\jquery-colorbox\jquery.colorbox.js <-- Not Found
"""

- But most of the files exist after: "res\vendor\flag-sprites.min.css", "res\vendor\jquery-colorbox\example3\colorbox.cs", "resources\vendor\jquery-legacy\dist\jquery.js", "resources\vendor\bootstrap-sass\assets\javascripts\bootstrap.js", "resources\vendor\jquery-colorbox\jquery.colorbox.js".
But the site looks ugly (has no bootstrap css included).
Any help apriciated.

br,
P

**Comment by mattisthenation** [comment]
I had the same issue. I ran the artisan migrate, then went and ran gulp again and it all seemed to work fine.

**Comment by MECU** [comment]
I simply ran gulp a second time and it worked for me.

**Comment by stojankukrika** [comment]
yea, sometimes gulp can make this problem. Run gulp again to solve it.
