### ISSUE TITLE
Install error: no config/local directory

### ISSUE THREAD

**Issue by MECU** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#162]
There is no ``config/local/`` directory.

https://github.com/mrakodol/Laravel-5-Bootstrap-3-Starter-Site#step-3-configure-mailer

**Comment by MECU** [comment]
A few other notes from my install:

I had to install gulp globally before it would work. ``npm install -g gulp``

I had to run gulp twice before it would fully generate the files. The first time, it only created ``all.css`` and ``all.js``. Running it a second time worked fine.

**Comment by stojankukrika** [comment]
OK. I will fix it in documentation. TNX :+1:
