### ISSUE TITLE
Article teaser and content are output with HTML tags

### ISSUE THREAD

**Issue by MECU** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#163]
Both the teaser and content are displayed with HTML tags:

    <p>Test</p>
    <p>test 123 asdf oihef oiwh efoih qwoiehf oqiewh foiqhe f</p>

![image](https://cloud.githubusercontent.com/assets/4950394/9592496/bcfb39fe-5000-11e5-88f8-becfd75b6d86.png)

**Comment by MECU** [comment]
Possibly related to #149

**Comment by stojankukrika** [comment]
I just post a new version. Can you download a new version and test it?

**Comment by MECU** [comment]
I manually implemented #161 and it fixed the problem.

Is there a preferred way to upgrade? Since I didn't use a composer method, it seems I have to download and overwrite all the files. But if I've made changes, I don't want to do that.

**Comment by stojankukrika** [comment]
it's Ok if you fixed the problem.If you wish you can leave only .env file and delete others and copy current files into that folder and install composer and gulp again. But if you didn't want to do it, you didn't need to.
