### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by microdesign** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#164]
Uncaught Error: Container does not exist: .circle.firstg @ plugins.js:9332.e @ plugins.js:933(anonymous function) @ scripts.js:164m.event.dispatch @ jquery.min.js:3m.event.add.r.handle @ jquery.min.js:3

**Comment by stojankukrika** [comment]
I just post a new version. Can you download a new version and test it?

**Comment by microdesign** [comment]
Can we update it with composer, because our website is in progress already?

**Comment by stojankukrika** [comment]
No you can't,because it's not only laravel vendor directory upaded. If you in development you can continue and self fix the errors if you had.I will helo you but I didn't have your code.

**Comment by MECU** [comment]
It is possible. I'm not sure of the technology, but it's essentially how WordPress manages updates doing line comparisons instead of global file replacements.

**Comment by stojankukrika** [comment]
I do not use wordpress so I do not know how do they work :(
