### ISSUE TITLE
What about the famous Repository pattern ?!

### ISSUE THREAD

**Issue by imanghafoori1** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#166]
If you agree I can implement the repository pattern and submit push request.

**Comment by stojankukrika** [comment]
If you wish, you can do it.

**Comment by SuperlativeEntity** [comment]
This is a must have :)

**Comment by stojankukrika** [comment]
Can you show me how it's look like?

**Comment by SuperlativeEntity** [comment]
I know it says Laravel 4, but the principle is the same: http://culttt.com/2013/07/08/creating-flexible-controllers-in-laravel-4-using-repositories/

**Comment by stojankukrika** [comment]
I think that I use it already.
