### ISSUE TITLE
Class 'App\Providers\AuthServiceProvider' not found in

### ISSUE THREAD

**Issue by Timures** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#167]
Hi, first big thanks for your work.
But when I downloaded and make composer install get an error: Class 'App\Providers\AuthServiceProvider' not found in /home/timures/Laravel-5-Bootstrap-3-Starter-Sit  
  e-master/vendor/laravel/framework/src/Illuminate/Foundation/ProviderReposit  
  ory.php on line 146

**Comment by gjmacd** [comment]
I get the same issue.

**Comment by stojankukrika** [comment]
I fixed it now.I find that laravel add this file in new 5.1.11 version. TNX for issue :+1:
