### ISSUE TITLE
photo upload

### ISSUE THREAD

**Issue by tpfuhl** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#169]
How about the photo upload ? Cannot get it work. Something missing ?

**Comment by stojankukrika** [comment]
Did you get some error or something?

**Comment by tpfuhl** [comment]
Hello Stojan,
thank you for your quick feedback.
I do not get any error, neither apache nor php nor javascript, but the file
is not uploaded. Nevertheless, the uploadfolder is writable by www-data.
The form input field "image" is actually not filled in, after having
selected an image file from the local hard disk, and pressed the green
submit button. Hence, the upload mecanism does even not start.
Any ideas
Best,
thomas

2015-09-09 9:40 GMT+02:00 Stojan Kukrika <notifications@github.com>:

**Comment by stojankukrika** [comment]
Did you create album first?

**Comment by tpfuhl** [comment]
I put it into an existing album.

here is the URL:
http://ulivo.proportiodivina.eu/public

admin@admin.com / admin

th

2015-09-09 10:27 GMT+02:00 Stojan Kukrika <notifications@github.com>:

**Comment by stojankukrika** [comment]
Can you do this? Delete all files from your dev server and try again install it? I now fix some issue and you help me a loot if you want to do that, to know is this work now. Can you, please?

**Comment by tpfuhl** [comment]
Yes, that's ok for me ! Thanks for helping :-)
By th way, when we are in the admin dashboard, the logout button has
disappereared.

th

2015-09-09 11:27 GMT+02:00 Stojan Kukrika <notifications@github.com>:

**Comment by stojankukrika** [comment]
Ok. Wait then a minute till I add it.

**Comment by stojankukrika** [comment]
You can do it now.

**Comment by tpfuhl** [comment]
some infos on my working environment:

ubuntu 14.04 LTS

"npm install" outputs:

npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current:
{"node":"0.10.40","npm":"1.4.28"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current:
{"node":"0.10.40","npm":"1.4.28"})
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current:
{"node":"0.10.40","npm":"1.4.28"})
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current:
{"node":"0.10.40","npm":"1.4.28"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current:
{"node":"0.10.40","npm":"1.4.28"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current:
{"node":"0.10.40","npm":"1.4.28"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current:
{"node":"0.10.40","npm":"1.4.28"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current:
{"node":"0.10.40","npm":"1.4.28"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current:
{"node":"0.10.40","npm":"1.4.28"})
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
-
> node-sass@3.3.2 install
/var/www/html/prodiv/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at
/var/www/html/prodiv/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-11/binding.node

> node-sass@3.3.2 postinstall
/var/www/html/prodiv/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

`
/var/www/html/prodiv/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-11/binding.node
` exists.
 testing binary.
Binary is fine; exiting.

"gulp" running twice.

 php artisan key:generate



2015-09-09 11:41 GMT+02:00 Thomas Pfuhl <pfuhlthomas@gmail.com>:

**Comment by stojankukrika** [comment]
I do not know where is problem, nodejs have some problem,I suppose, in my home localhost works well.

**Comment by tpfuhl** [comment]
probably nodejs causes the problem, may be because of the version 0.10.40
(required is 0.12.0).
It is an issue of the client side since the uploaded file is not passed to
the submit handler.

I have now installed your latest version on my devserver
http://ulivo.proportiodivina.eu/public
when trying to submit the edit or create form with an selected file, tehre
is even no popiup message " proceeding" (as I saw this on your demo site).
So the file is not even processed.
Debian/Ubuntu only ships node 0.10.40, it is a bit tricky to try installing
a newer version.

Well, thank you for your help !
Thomas (currently in Berlin)

2015-09-09 12:00 GMT+02:00 Stojan Kukrika <notifications@github.com>:

**Comment by tpfuhl** [comment]
Is it worth to try  using a "normal" upload form with  a "normal" submit
handler on teh server side, thus keeping aside nodejs ?
th

2015-09-09 12:11 GMT+02:00 Thomas Pfuhl <pfuhlthomas@gmail.com>:

**Comment by stojankukrika** [comment]
Can you replace last file versions, from my last commit(you can see it in this project in commits) and try again with upload photo?

**Comment by tpfuhl** [comment]
I am very sorry, it does still not upload the file.
th

2015-09-09 13:01 GMT+02:00 Stojan Kukrika <notifications@github.com>:

**Comment by HighFlyerPL185** [comment]
I am having the same issue, no photo is being uploaded to the directory. The record gets added, and is visible in the admin panel, but when you edit the photo and go down to where the Browse button is, it says there is no file.

**Comment by stojankukrika** [comment]
OK. Tnx for info. I will type here when I solve this problem.

**Comment by stojankukrika** [comment]
It fixed not and all works.

**Comment by tim-peterson** [comment]
I'm also not able to do photo upload. I don't get an error but no directories are created. I just downloaded the app a few days ago and see you've made some changes. Should I just copy/paste all the changes from your most recent commits? Can you explain what you changed to make it work? I'm new to Laravel.

**Comment by stojankukrika** [comment]
Download again and replace files.Change forms and logic to save images.

**Comment by tpfuhl** [comment]
working like a charm now. Many thanks !
Thomas

2015-09-10 6:11 GMT+02:00 Stojan Kukrika <notifications@github.com>:

**Comment by stojankukrika** [comment]
TNX Tomas.
