### ISSUE TITLE
Gulp failing because /resources/vendor/ is empty

### ISSUE THREAD

**Issue by net-split** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#171]
So I followed the install instructions.
When I run gulp it fails to create the .css because it says some file are missing (which they are).
Inside the  /resources/vendor/ directory I only find a .gitignore file.
The only file Gulp creates is /public/admin.css - no js files either.

![error](https://cloud.githubusercontent.com/assets/14207106/9775981/0a3f2072-5754-11e5-8d90-91924c2b7089.png)

I ready in a different issue thread to just run Gulp again. That didn't solve the issue. Same errors, still no files being created. 

What am I doing wrong?

**Comment by stojankukrika** [comment]
I think that bower didn't work on your host. Did you install nodejs and use "npm install" after that? And then after that finish use gulp?

**Comment by net-split** [comment]
Thanks you for the fast answer!
Yes, I gulp and ran npm install prior to using gulp. However I got some "minor" error that optional dependencies failed:
![error](https://cloud.githubusercontent.com/assets/14207106/9787434/18fd149c-57c3-11e5-9e5c-f8d7df0f9aa4.png)

**Comment by topsub** [comment]
I'm currently seeing this issue, I did a pull ran all the commands but still see my gulp fails because resource/vender is empty. What command is suppose to put files into resource/vender?

**Comment by net-split** [comment]
I ran gulp probably 10 times now without success. Any ideas what to do?

**Comment by topsub** [comment]
well posting error messages will help. confirm you have node installed? confirm you have all the files downloaded. like my issue for what ever reason the (DOT) files didn't download or removed or what ever happen to them.

**Comment by net-split** [comment]
I do have a .bowerrc file in the main folder.
I posted both the error messages above. It was basically the same as yours.

**Comment by topsub** [comment]
post the output of when you run gulp

**Comment by net-split** [comment]
Thats what I get (the git error is not relevant i think):

![errororor](https://cloud.githubusercontent.com/assets/14207106/9824631/73cc4cb0-58ce-11e5-8e13-fdac1336b473.png)

**Comment by topsub** [comment]
delete your node_modules folder and start at the top of the instructions.

composer install
npm install
gulp

**Comment by net-split** [comment]
All right did it. Still the same error, vendors files are missing.
Where should the vendors files be coming form anyways? Is gulp supposed to get them?

**Comment by topsub** [comment]
paste your folder so we can see folders and files.

**Comment by net-split** [comment]
Ok:
![files](https://cloud.githubusercontent.com/assets/14207106/9825195/022ee348-58d2-11e5-93ca-fc64cd656c35.png)

**Comment by topsub** [comment]
open up resources and vender, I assume its still empty? so something isn't firing to populate that folder from bower

**Comment by topsub** [comment]
also run npm install --verbose and post the results.

**Comment by net-split** [comment]
I see, it is not completely empty. But the files gulp is complaining about are in fact missing:
![files2](https://cloud.githubusercontent.com/assets/14207106/9825452/acc980e6-58d3-11e5-8bd4-ac854eb315e5.png)

![verbase](https://cloud.githubusercontent.com/assets/14207106/9825465/c1f9108a-58d3-11e5-9c25-56fff9f48553.png)

**Comment by chrismuench** [comment]
I would chime in saying I'm getting this same error saying the same files are missing.
```
Chriss-MacBook-Pro:L5App chrismuench$ gulp
[13:14:42] Using gulpfile ~/Code/L5App/gulpfile.js
[13:14:42] Starting 'default'...
[13:14:42] Starting 'task'...
[13:14:42] Starting 'bower'...
[13:14:42] Using cwd:  /Users/chrismuench/Code/L5App
[13:14:42] Using bower dir:  ./bower_components
[13:14:42] Finished 'task' after 6.64 ms
[13:14:42] Starting 'copy'...

Fetching Copy Source Files...
   - resources/vendor/bootstrap/dist/fonts/bootstrap/**/**/*


Saving To...
   - public/fonts

[13:14:43] Finished 'default' after 59 ms
[13:14:43] Finished 'copy' after 482 ms
[13:14:43] Starting 'copy'...

Fetching Copy Source Files...
   - resources/vendor/font-awesome/fonts/**/**/*


Saving To...
   - public/fonts

[13:14:43] Finished 'copy' after 11 ms
[13:14:43] Starting 'copy'...

Fetching Copy Source Files...
   - resources/vendor/jquery-colorbox/example3/images/**/**/*


Saving To...
   - public/css/images

[13:14:43] Finished 'copy' after 10 ms
[13:14:43] Starting 'copy'...

Fetching Copy Source Files...
   - resources/vendor/jquery-ui/themes/base/images/**/**/*


Saving To...
   - public/css/images

[13:14:43] Finished 'copy' after 4.48 ms
[13:14:43] Starting 'copy'...

Fetching Copy Source Files...
   - resources/vendor/flag-sprites/dist/css/flag-sprites.min.css <-- Not Found


Saving To...
   - public/css/flags.css

[13:14:43] Finished 'copy' after 5.55 ms
[13:14:43] Starting 'copy'...

Fetching Copy Source Files...
   - resources/vendor/flag-sprites/dist/img/flags.png <-- Not Found


Saving To...
   - public/img/flags.png

[13:14:43] Finished 'copy' after 9.02 ms
[13:14:43] Starting 'styles'...

Fetching Styles Source Files...
   - resources/vendor/bootstrap/dist/css/bootstrap.css <-- Not Found
   - resources/vendor/bootstrap/dist/css/bootstrap-theme.css <-- Not Found
   - resources/vendor/font-awesome/css/font-awesome.css <-- Not Found
   - resources/vendor/bootswatch/simplex/bootstrap.css <-- Not Found
   - resources/vendor/jquery-colorbox/example3/colorbox.css <-- Not Found
   - resources/vendor/Justified-Gallery/dist/css/justifiedGallery.css <-- Not Found


Saving To...
   - public/css/site.css

[13:14:43] Finished 'styles' after 179 ms
[13:14:43] Starting 'scripts'...

Fetching Scripts Source Files...
   - resources/vendor/jquery/dist/jquery.js <-- Not Found
   - resources/vendor/bootstrap/dist/js/bootstrap.js <-- Not Found
   - resources/vendor/jquery-colorbox/jquery.colorbox.js <-- Not Found
   - resources/vendor/Justified-Gallery/dist/js/jquery.justifiedGallery.js <-- Not Found


Saving To...
   - public/js/site.js

[13:14:44] Finished 'scripts' after 813 ms
[13:14:44] Starting 'styles'...

Fetching Styles Source Files...
   - resources/vendor/bootstrap/dist/css/bootstrap.css <-- Not Found
   - resources/vendor/jquery-ui/themes/base/jquery.ui.all.css <-- Not Found
   - resources/vendor/bootstrap/dist/css/bootstrap-theme.css <-- Not Found
   - resources/vendor/font-awesome/css/font-awesome.css <-- Not Found
   - resources/vendor/bootswatch/simplex/bootstrap.css <-- Not Found
   - resources/vendor/jquery-colorbox/example3/colorbox.css <-- Not Found
   - resources/vendor/datatables/media/css/dataTables.bootstrap.css <-- Not Found
   - resources/vendor/datatables-bootstrap3-plugin/media/css/datatables-bootstrap3.css <-- Not Found
   - resources/vendor/metisMenu/dist/metisMenu.css <-- Not Found
   - resources/vendor/summernote/dist/summernote.css <-- Not Found
   - resources/vendor/summernote/dist/summernote-bs3.css <-- Not Found
   - resources/vendor/select2/dist/css/select2.css <-- Not Found
   - resources/assets/css/sb-admin-2.css


Saving To...
   - public/css/admin.css

[13:14:44] gulp-notify: [Laravel Elixir] Stylesheets Merged!
[13:14:44] Finished 'styles' after 52 ms
[13:14:44] Starting 'scripts'...

Fetching Scripts Source Files...
   - resources/vendor/jquery/dist/jquery.js <-- Not Found
   - resources/vendor/jquery-ui/ui/jquery.ui.core.js <-- Not Found
   - resources/vendor/bootstrap/dist/js/bootstrap.js <-- Not Found
   - resources/vendor/jquery-colorbox/jquery.colorbox.js <-- Not Found
   - resources/vendor/datatables/media/js/jquery.dataTables.js <-- Not Found
   - resources/vendor/datatables/media/js/dataTables.bootstrap.js <-- Not Found
   - resources/vendor/datatables-bootstrap3-plugin/media/js/datatables-bootstrap3.js <-- Not Found
   - resources/vendor/datatables-responsive/js/dataTables.responsive.js <-- Not Found
   - resources/vendor/metisMenu/dist/metisMenu.js <-- Not Found
   - resources/vendor/summernote/dist/summernote.js <-- Not Found
   - resources/vendor/select2/dist/js/select2.js <-- Not Found
   - resources/assets/js/bootstrap-dataTables-paging.js
   - resources/assets/js/dataTables.bootstrap.js
   - resources/assets/js/datatables.fnReloadAjax.js
   - resources/assets/js/sb-admin-2.js


Saving To...
   - public/js/admin.js

[13:14:44] gulp-notify: [Laravel Elixir] Scripts Merged!
[13:14:44] Finished 'scripts' after 51 ms
[13:14:46] Finished 'bower' after 3.33 s
```

**Comment by ktly** [comment]
Had the same problem. It looks like bower installs all dependencies into `bower_compontent` and not to `resources_vendor`.

For me this did the trick:

    cp -rf bower_components assets/vendor

**Comment by ktly** [comment]
Got it.

It looks that (at least on Linux) when you're copying/moving files using wildcard, dot-files are not being copied. And when you miss those (I guess it's about `.bowerrc`), bower doesn't move the files from `bower_components`.

Previously, I was installing the project by unzipping the archive in the target directory and then doing `mv Laravel-5-Bootstrap-3-Starter-Site/* .` .And thus I didn't have (among others) `.bowerrc`.

After unpacking, renaming the dir (instead of moving files) and then performing the installation, everything works without problems.

**Comment by stojankukrika** [comment]
Can you create pull request for that or something?

**Comment by ktly** [comment]
There's nothing to do, really. The above problem happens, when the project is missing files. With all of the files present, there's no problem, at least that's what happened in my case.

Unix users just have to remember, that if they want to move a project, they need to do both:

    mv project/* new-dir
    mv project/.* new-dir

**Comment by net-split** [comment]
I do not have the bower_compontents folder either.

**Comment by nextpulse** [comment]
Same issues as reported by others :(

**Comment by topsub** [comment]
i installed fresh copy today and made sure the dot files were included and everything worked perfect.

**Comment by nextpulse** [comment]
So is how i resolved some of the issues:

i) Do not use the zip (it is missing some .files). Clone the source instead.
ii) Seems there is a possible circular dependency issue in the gulpfiles. So run the gulp command twice.

**Comment by net-split** [comment]
I cloned the source with github and ran all the commands. Files are still missing, same problem as before.

Could it be that the problem is somehow related to using Windows 7 64?

**Comment by myirongarden** [comment]
i just cloned source and ran:

composer install
npm install
gulp
gulp

2th time i ran gulp everything was green :0)

**Comment by stojankukrika** [comment]
Now I put all generated gulp files so you can use it without gulp
