### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by Odenda1** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#173]
Good day,

I have followed all the steps and got the site up and running. When I click on any of the links I get a 404.0 Not Found error.

I am completely new to Laravel and have no idea where to begin.

I am running Windows 10, IIS 10, PHP 5.6.

Could you please assist in this regard.

**Comment by cklam** [comment]
Is you http firewall blocking https? Check your host

**Comment by stojankukrika** [comment]
I think that is global problem, because I see many people to create issue about that problem but I didn't find solution for that.

**Comment by Odenda1** [comment]
I am working on localhost and have disabled the firewall but the problem is still the same. I have also seen others with this problem and it seems to be with the web.config file. In other environments that is the .htaccess file.

**Comment by lorvent** [comment]
i guess its because of mod_rewrite (pretty URLs) issue

**Comment by Odenda1** [comment]
Can anyone suggest another similar project that I can use? It seems as though this project is impossible to get going. I have installed Apache and tried it on there but I am still unable to get it working.

mod_rewrite is installed and I simply cannot find a solution to this anywhere.

**Comment by lorvent** [comment]
hmm,
if you are fine with spending some money,
then you can check readme of this repo https://github.com/mrakodol/Laravel-5-Bootstrap-3-Starter-Site#more-advanced-one

**Comment by Odenda1** [comment]
Thanks for your help, I decided to go with a paid solution which offers me more than I need.

**Comment by stojankukrika** [comment]
OK.
