### ISSUE TITLE
alternative db

### ISSUE THREAD

**Issue by bflydesign** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#18]
Hello, in my homestead.yaml file I added a specific database for use with this starter-site.
So I changed the database-name in config/database.php to the one I added in my yaml-file but still the site is looking for tables in the homestead-database. Where can I change this?

PS migration and seeding succeeded

**Comment by stojankukrika** [comment]
Try now. Now is update to new laravel 5 so it my be work. Please tell me was now works?
