### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by mxmtsk** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#180]
I installed everything and it works perfectly except the admin Dashboard which is missing jQuery and CSS.

![Image of Error](http://oi58.tinypic.com/15yan36.jpg)

**Comment by mxmtsk** [comment]
my fault, sorry

**Comment by chenchaochen** [comment]
How you fixed it?
Thanks

**Comment by stojankukrika** [comment]
run gulp :)

**Comment by chenchaochen** [comment]
I'd run gulp twice before the issue. And I run gulp again after saw your response, and it worked. Weird though. 
Thanks :+1:
