### ISSUE TITLE
NotFoundHttpException in RouteCollection.php line 161:

### ISSUE THREAD

**Issue by joaomelont** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#181]
Hi!

After following the installation guide, I receive this error:

NotFoundHttpException in RouteCollection.php line 161:

**Comment by joaomelont** [comment]
Wow.. Sorry. My bad! Problem solved...

**Comment by chenchaochen** [comment]
I fixed the dashboard presentation problem after run gulp, but still got NotFoundHttpException in RouteCollection.php line 161 problem after clicked "view details" from the dashboard. Could you tell me how you fixed it?
Thanks

**Comment by strydor** [comment]
Umm, great @joaomelont! any more details there?
