### ISSUE TITLE
Running "Gulp --production" throws "Broken @import" error

### ISSUE THREAD

**Issue by michaeljhopkins** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#182]
Running `gulp` completes successfully. In an attempt to get minified files, running `gulp --production` results in the following error. 

```
Saving To...
   - public/css/admin.css


events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Broken @import declaration of "jquery.ui.theme.css"

real	9.65s
```

![](http://i.imgur.com/vy0YZlW.png)

**Comment by stojankukrika** [comment]
it's fixed in new version. Please get a new version
