### ISSUE TITLE
 changed to /resources/views/emails/password.blade.php but password link mail still  unable to send out.

### ISSUE THREAD

**Issue by richardwkf** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#184]
changed to /resources/views/emails/password.blade.php but password reset  link mail still  unable to send out.

/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php#137InvalidArgumentException

            }
        }

        throw new InvalidArgumentException("View [$name] not found.");
    }

    /**

**Comment by sanathpathiraja** [comment]
yes. I also have this problem

**Comment by stojankukrika** [comment]
fixed in new version. But also, do not forgot need to setup mail settings in .env file.
