### ISSUE TITLE
Crashed dashboard and NotFoundHttpException in RouteCollection.php line 161

### ISSUE THREAD

**Issue by chenchaochen** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#188]
Hi, 
When I clicked on the dashboard, it showed abnormally as below. 
![screenhunter_18 nov 27 14 56](https://cloud.githubusercontent.com/assets/13834948/11435591/117b3898-9517-11e5-8bf5-70fd39755be0.jpg)

Clicked "View Details" on dashboard, it gave me the NotFoundHttpException in RouteCollection.php line 161.
![image](https://cloud.githubusercontent.com/assets/13834948/11435700/50c10874-9518-11e5-9e78-d752ed126aee.png)
How to fix it?
Thanks

**Comment by chenchaochen** [comment]
The first view issue was fixed after run gulp, but second one NotFoundHttpException still remained.

**Comment by stojankukrika** [comment]
now it's fixed in new version. Please get a new version
