### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by zcosmin20** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#191]
[13:33:13] LOG.error: exception 'InvalidArgumentException' with message 'Cannot end a section without first starting one.' in D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php:14106
Stack trace:
#0 D:\wamp\www\laravel5startersite\storage\framework\views\a20fee67f21928ec162f4426c9a32d8b(77): Illuminate\View\Factory->stopSection()
#1 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(14602): include('D:\\wamp\\www\\lar...')
#2 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(14638): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\\wamp\\www\\lar...', Array)
#3 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(14471): Illuminate\View\Engines\CompilerEngine->get('D:\\wamp\\www\\lar...', Array)
#4 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(14459): Illuminate\View\View->getContents()
#5 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(14450): Illuminate\View\View->renderContents()
#6 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(15599): Illuminate\View\View->render()
#7 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(15114): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#8 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(7684): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#9 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(8911): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#10 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9581): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9563): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(8912): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(8897): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\HomeController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#16 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(7851): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'index')
#17 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(7822): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#18 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(7475): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9581): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9563): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(7476): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(7464): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#25 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(7449): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#26 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(2302): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#28 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9581): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 D:\wamp\www\laravel5startersite\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9573): call_user_func_array(Array, Array)
#32 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(2926): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9573): call_user_func_array(Array, Array)
#35 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(12925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9573): call_user_func_array(Array, Array)
#38 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(11532): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9573): call_user_func_array(Array, Array)
#41 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(12666): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9573): call_user_func_array(Array, Array)
#44 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(12605): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9573): call_user_func_array(Array, Array)
#47 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(2979): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9573): call_user_func_array(Array, Array)
#50 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9563): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(2249): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#53 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(2232): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#54 D:\wamp\www\laravel5startersite\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#55 {main}

Next exception 'ErrorException' with message 'Cannot end a section without first starting one. (View: D:\wamp\www\laravel5startersite\resources\views\pages\home.blade.php)' in D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php:14106
Stack trace:
#0 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(14604): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(InvalidArgumentException), 1)
#1 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(14638): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\\wamp\\www\\lar...', Array)
#2 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(14471): Illuminate\View\Engines\CompilerEngine->get('D:\\wamp\\www\\lar...', Array)
#3 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(14459): Illuminate\View\View->getContents()
#4 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(14450): Illuminate\View\View->renderContents()
#5 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(15599): Illuminate\View\View->render()
#6 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(15114): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(7684): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(8911): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9581): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9563): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(8912): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(8897): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\HomeController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#15 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(7851): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'index')
#16 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(7822): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#17 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(7475): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9581): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9563): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(7476): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(7464): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#24 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(7449): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#25 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(2302): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#27 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9581): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 D:\wamp\www\laravel5startersite\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9573): call_user_func_array(Array, Array)
#31 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(2926): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9573): call_user_func_array(Array, Array)
#34 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(12925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9573): call_user_func_array(Array, Array)
#37 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(11532): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9573): call_user_func_array(Array, Array)
#40 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(12666): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9573): call_user_func_array(Array, Array)
#43 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(12605): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9573): call_user_func_array(Array, Array)
#46 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(2979): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9573): call_user_func_array(Array, Array)
#49 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(9563): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(2249): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 D:\wamp\www\laravel5startersite\bootstrap\cache\compiled.php(2232): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#53 D:\wamp\www\laravel5startersite\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#54 {main}
errorlog

http://prntscr.com/9930t0

http://prntscr.com/99313e

**Comment by lethality** [comment]
Dunno if you found a fix yourself, but you can fix this error by removing the @stop at the end of line 2 in the offending file

**Comment by stojankukrika** [comment]
now it's fixed
