### ISSUE TITLE
ACL needs to be fixed

### ISSUE THREAD

**Issue by cabillier** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#192]
regular user can access the admin page...

if they are going to access routes other than admin/dashboard...

http://localhost/site/public/admin/user
http://localhost/site/public/admin/photo

and etc

**Comment by chrismedina** [comment]
Yes,

	public function authorize()
	{
		return true;
	}

Seems to be the issue in all of the requests.

**Comment by cklam** [comment]
Thanks buddy ! You nailed it!

**Comment by stojankukrika** [comment]
fixed in new version

**Comment by cklam** [comment]
I will take a look
