### ISSUE TITLE
After Install home.blade.php problem

### ISSUE THREAD

**Issue by tolgacelik** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#194]
Hi, I'm having a problem. I appreciate if you can help.

ErrorException in compiled.php line 14130:
Cannot end a section without first starting one. (View: C:\xampp\htdocs\laravel\cms\resources\views\pages\home.blade.php)

Thanks..

**Comment by swaylay** [comment]
I received same problem.

**Comment by gibbo3003** [comment]
I believe this was mentioned before and you just remove the @stop at the end of the file.

**Comment by dvolve** [comment]
Nice one Gibbo ;)

**Comment by swaylay** [comment]
I found that my issue was not installing bower correctly. It did yield the same error.

**Comment by guruguruman** [comment]
@gibbo3003 It solved mine too, big thanks!
