### ISSUE TITLE
After install fix home.blade , backend admin not work

### ISSUE THREAD

**Issue by Jakkawad** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#195]
after install backend show me
<img width="1280" alt="screen shot 2558-12-17 at 03 22 01" src="https://cloud.githubusercontent.com/assets/12533828/11852925/60ff2266-a46d-11e5-967c-d35b36a1c71b.png">

how to fix

thank you

**Comment by gozals** [comment]
same here, any solution?

**Comment by TesoMayn** [comment]
I had this issue, but mine was because I was loading the resources over HTTP instead of HTTPS

**Comment by physio** [comment]
i have the same problem

**Comment by Chandler95** [comment]
same issue here

**Comment by stojankukrika** [comment]
problem solved. run again gulp get new packages.

**Comment by reypm** [comment]
@stojankukrika I am running this same issue with the latest release, can you help me out?
