### ISSUE TITLE
Illegal string offset 'searchable'

### ISSUE THREAD

**Issue by acfabro** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#198]
While DataTables is "ajaxing" data from the server (this specific instance happened in the admin section):

![image](https://cloud.githubusercontent.com/assets/11073791/12375299/adb45602-bcf6-11e5-9507-d3e587a6980c.png)

Which leads to this:

![image](https://cloud.githubusercontent.com/assets/11073791/12375312/221b133c-bcf7-11e5-9caa-e8bae4b9739f.png)

Here is the url of the http call: http://myserver/admin/user/data?draw=1&columns%5B0%5D%5Bdat…art=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1452991348897

EDIT: BTW, this is a fresh install. No code has been edited yet.

**Comment by stojankukrika** [comment]
fixed in new version
