### ISSUE TITLE
error when accessing article section (admin)

### ISSUE THREAD

**Issue by razor9999** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#199]
SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'order clause' (SQL: select `articles`.`id`, `articles`.`title`, `article_categories`.`title` as `category`, `languages`.`name`, `articles`.`created_at` from `articles` inner join `languages` on `languages`.`id` = `articles`.`language_id` inner join `article_categories` on `article_categories`.`id` = `articles`.`article_category_id` where `articles`.`deleted_at` is null order by `0` asc limit 10 offset 0)

**Comment by webacers** [comment]
I've same problem in article and article categories

**Comment by webacers** [comment]
changing "serverSide": false in admin/layouts/default.blade.php  works.

**Comment by PhanHaHus** [comment]
thanks webacers  so much :D

**Comment by stojankukrika** [comment]
thanks webacers :+1:
