### ISSUE TITLE
Error with yajra/laravel-datatables, throw a exception:"order by '0'" by demo

### ISSUE THREAD

**Issue by fannur** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#201]
Solution:
https://github.com/yajra/laravel-datatables/commit/43a5fb178636828996d0a4d1b32b819447f51c03

**Comment by Ju1jan** [comment]
Hey.

Hardcode like this this helped me (temporally).
```
if (isset($_GET['order'][0]['column']) && '0' === (string) $_GET['order'][0]['column']) {
        unset($_GET['order'][0]);
}
```

But better way is to update datatable dependency to higher version.
> "yajra/laravel-datatables-oracle" : "~6.0"

The instruction how to upgrade from v5.x to v6.x is above or here:
https://github.com/yajra/laravel-datatables#upgrading-from-v5x-to-v6x

Thank you, @fannur

**Comment by stojankukrika** [comment]
now it's fixed
