### ISSUE TITLE
How to include all dependencies for composer?

### ISSUE THREAD

**Issue by Ju1jan** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#205]
Hello. Tell me please, what did i wrong in setup?
As I know, the "composer install" command does not work without autoload.php file.

My steps are:
1. $ composer install
Got fatal error: "Failed opening required '../vendor/autoload.php' botstrap/autoload.php on line 17 "

2. $ composer dump-autoload
The autoload file was generated in the vendor directory.

3. $ composer install
"Error Output: PHP Fatal error:  Class 'Illuminate\Foundation\Application'"

All packages (npm, composer, gulp) are installed in my system. I can start and use clean Laravel setup without problem.
And i did not found in your readme.md line about "npm install --save-dev gulp" I did it to be able use gulp.

Tell me please what's wrong here?
Thank you very much in advance

**Comment by Ju1jan** [comment]
It seems i found solution.
"composer install --no-scripts" after "dumpautoload" helped me.
But it would be great have it in readme :)

**Comment by jnuc093** [comment]
Great .I meet the same problems and resolved with your steps.

**Comment by TiDJ** [comment]
same here :) Thanks

**Comment by diegodm2** [comment]
thanks @Ju1jan

**Comment by byAliyev** [comment]
many thanks **Ju1jan**

**Comment by stojankukrika** [comment]
many thanks Ju1jan - added into readme
