### ISSUE TITLE
In step 3 , error  require() : Failed opening requierd  on line 17 script php artisan clear-compiled handling the pre-upda-cmd event returned with an error 

### ISSUE THREAD

**Issue by siamakgoudarzi** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#206]
Hi in step 3 when i type composer install then  :

warning : require c:\xampp\htdocs\s5\bootstrap/../vendor/autoload.php : failed to open stream : No such file or directory in c:\apm\php\PEAR in c:\xamp\htdocs\bootstrap\autoload.php on line 17

fatal error  : require() : Failed opening requierd c:\xampp\htdocs\s5\bootstrap/../vendor/autoload.php  , include_path ='.;c:\apm\php\PEAR in c:\xamp\htdocs\bootstrap\autoload.php on line 17
script php artisan clear-compiled handling the pre-upda-cmd event returned with an error 
[runtimeExecption]
error ouput :
install [ --prefer-source] [ --prefer-dist] [--dr-run] [--dev] ... 
![image](https://cloud.githubusercontent.com/assets/7514876/15105306/e620e3f6-15d5-11e6-989e-837b1a741172.png)

Cmd run as administrative  , environment variable set to C:\xampp\htdocs\s5  , s5 name of my project , Use Xampp , windows 8.1 64 bit.
Thanks

**Comment by stojankukrika** [comment]
Please run commands in 2. step:
    composer dump-autoload
   composer install --no-scripts
