### ISSUE TITLE
How to use it with Laravel 5.2 ?

### ISSUE THREAD

**Issue by osnwach** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#208]
I like the project of this starter site !

Please, I will like to use it with Laravel 5.2

What do I need to do ?

or when are you upgrading it to Laravel 5.2 ?

**Comment by stojankukrika** [comment]
Wll soon will be l5.3 relaced so I think that will be nice to migrate it to Laravel 5.3. then 5.2.But if you have time you can do it :)

**Comment by goowikns** [comment]
Any news about it or ETA when it will be updated to Laravel 5.3?
