### ISSUE TITLE
Not ableto upload the image

### ISSUE THREAD

**Issue by prakashjha1956** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#209]
HI,
I am not able to upload the image , please check it
http://laravel.customerparadise.in/
UserId: admin@admin.com
Pass:  admin

**Comment by stojankukrika** [comment]
I think that need to setup permission chmod 777 to "public/appfiles/photoalbum"

**Comment by prakashjha1956** [comment]
yes....now it is working fine,thanks
