### ISSUE TITLE
I got this after following all steps , any help please?

### ISSUE THREAD

**Issue by amanySaad** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#211]
![image](https://cloud.githubusercontent.com/assets/7767837/16176254/e9b551e2-3609-11e6-94b7-fc249cd43da7.png)

**Comment by stojankukrika** [comment]
Hi.You didn't follow all steps.You didn't run gulp to make js and css files.

**Comment by amanySaad** [comment]
Thanks , It works fine but now I want to define jQuery so I added these lines on package.json file
I added these lines on package.json file 
"eslintConfig": {
        "env": {
            "jquery ": true
        }
    }
but jquery stil n't defined...any help?

**Comment by stojankukrika** [comment]
Delete it, and before run gulp, try to run this command:

  gulp bower --force-latest
