### ISSUE TITLE
JQuery not defined

### ISSUE THREAD

**Issue by amanySaad** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#212]
I want to add some JS code , I create anew js file in "public/js " but I have a message
"ReferenceError: jQuery is not defined"

any help?

**Comment by terrorfall** [comment]
This is till present in latest build. Fresh install I get 

`Uncaught ReferenceError: $ is not defined`

On both admin.js:2 and dashboard:217

**Comment by stojankukrika** [comment]
you didn't run gulp and didn't read readme file step by step.

**Comment by terrorfall** [comment]
I did, the problem only applies to the admin section, not the rest of the site.
