### ISSUE TITLE
new crud

### ISSUE THREAD

**Issue by amanySaad** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#213]
I want to add a new  crud , I create routes,controller,model,request ,views,seeds and schema
I can now shoow list from my new table and insert anew one record but when I make edit  or delete no query execute and the object of request return empty because id of selected record n't sent 
I wondered if I forget to make thing
![image](https://cloud.githubusercontent.com/assets/7767837/16358935/1cdd8544-3b23-11e6-9a13-e62ae720f52b.png)
when make edit this is the output of var_dump($service) object 
![image](https://cloud.githubusercontent.com/assets/7767837/16358955/9d1538e2-3b23-11e6-8702-bca119d5b633.png)

**Comment by stojankukrika** [comment]
Can you show the code of your Controller?Maybe there you miss something.

**Comment by amanySaad** [comment]
[ServiceController.txt](https://github.com/mrakodol/Laravel-5-Bootstrap-3-Starter-Site/files/333466/ServiceController.txt)

**Comment by stojankukrika** [comment]
Hm...Conroller looks ok.Maybe you didn't model bin in route file.Please look at route.php file.

**Comment by amanySaad** [comment]
[Service.txt](https://github.com/mrakodol/Laravel-5-Bootstrap-3-Starter-Site/files/333502/Service.txt)
[ServiceRequest.txt](https://github.com/mrakodol/Laravel-5-Bootstrap-3-Starter-Site/files/333503/ServiceRequest.txt)

Routes:
 # Service
    Route::get('service/data', 'Admin\ServiceController@data');
    Route::get('service/{service}/show', 'Admin\ServiceController@show');
    Route::get('service/{service}/edit', 'Admin\ServiceController@edit');
    Route::get('service/{service}/delete', 'Admin\ServiceController@delete');
    Route::resource('service', 'Admin\ServiceController');

**Comment by stojankukrika** [comment]
I think you need to add:
Route::model('service', 'App\Service');
after:
Route::model('user', 'App\User');

**Comment by amanySaad** [comment]
It works fine now , thanks alot for your support :)

**Comment by stojankukrika** [comment]
It's ok :)
