### ISSUE TITLE
Cannot  access admin panel on Demo site

### ISSUE THREAD

**Issue by nepal12** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#22]
In the demo site "http://l5start.mrakodol.info/" Login with "admin@admin.com" and "admin" is possible but it is not possible to enter the admin panel.

**Comment by stojankukrika** [comment]
I do not know what is the problem. On may localhost works correctly. But, I will fix it when I rewrite this starter site when L5 released,to many things changed.

**Comment by nepal12** [comment]
Is there anything that I can do.

**Comment by nepal12** [comment]
Is it possible to upload/send your local working complete folder and db to me.

**Comment by stojankukrika** [comment]
ofc :) but I need a email or server to upload it :)

**Comment by stojankukrika** [comment]
now I see that all code is in this project and database too :)

**Comment by stojankukrika** [comment]
I find problem..someone is play and change admin role in demo site :D

**Comment by nepal12** [comment]
can you use this : https://www.box.com/ . We can use this as upload site
