### ISSUE TITLE
Unable to change a users password

### ISSUE THREAD

**Issue by beardedgeek** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#24]
When trying to change the admin password, I get the following error. Note, the password is unhashed!

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'password_confirmation' in 'field list' (SQL: update `users` set `password` = Password, `updated_at` = 2015-02-01 15:59:10, `password_confirmation` = Password where `id` = 1)

**Comment by stojankukrika** [comment]
+1 THANK you very much for this issue, fixed now!
