### ISSUE TITLE
Adding new role creates it twice

### ISSUE THREAD

**Issue by beardedgeek** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#25]
Replicate by going to the roles section within the admin panel and adding a new role. Press "create" and the light box goes white with no feedback. Click off the light box and the role is now in the list twice.

If you remove one of the duplicates, you get the following error

> FatalErrorException in RoleController.php line 146:
> Error: Call to a member function delete() on a non-object

Click off the light box and the duplicate role has now gone, leaving only one.

**Comment by beardedgeek** [comment]
Further to this, you only get the error above if you delete the first of the two new roles that are added. If you delete the second one, the light box goes white so no feedback, but it does delete successfully with no error.

**Comment by stojankukrika** [comment]
+1 THANK you very much for this issue, I hope that fixed now!
