### ISSUE TITLE
login: commit #fce9...

### ISSUE THREAD

**Issue by illuminate3** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#28]
Thanks for the update!

Reinstalled with the new commit and now when I go to login it just redirects to home. No error flash message so I'm not sure yet what the issue is. If I get a chance today, I'll try to debug the issue.

**Comment by stojankukrika** [comment]
TNX but it is not finished..I just update framework and move some controllers and items in right place. And I know about that problem, and you will helps me a loot if you find where is error and how to fix it.

**Comment by mehrdd** [comment]
Same problem here.

**Comment by illuminate3** [comment]
From what I got to test, login (Auth::attemp) goes through but it fails there ... I didn't have a chance to dig further. I'm still not sure why the token isn't working either ....

**Comment by scangroup** [comment]
I found that the public/index.php file was missing some data on the bottom that prevents session data from being saved.  This did not fix itself with a composer update, so I had to paste the following into index.php

```
$kernel = $app->make('Illuminate\Contracts\Http\Kernel');

$response = $kernel->handle(
	$request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);
```

**Comment by mehrdd** [comment]
thanks @scangroup 
it solved the problem.

**Comment by cklam** [comment]
Same here! Redirect to home!

**Comment by illuminate3** [comment]
Didn't fix it for me ... oh well.

**Comment by stojankukrika** [comment]
+1 THANK you very much @scangroup!
