### ISSUE TITLE
Admin Routes controller reference & csrf Middleware

### ISSUE THREAD

**Issue by scangroup** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#29]
I found that the references to the controllers in admin_routes.php needed to be adjusted.

rather than:
`Route::get('video', 'App\Http\Controllers\Admin\VideoController@index');`

It just needed to be
`Route::get('video', 'Admin\VideoController@index');`

This applies to all controller references in admin_routes.php

In addition, I needed to comment/remove the csrf middleware line in AdminController::__construct()

```
<?php namespace App\Http\Controllers;

class AdminController extends BaseController {

    /**
     * Initializer.
     *
     * @return \AdminController
     */
    public function __construct()
    {
        parent::__construct();
        //$this->middleware('csrf');
        $this->middleware('auth');
        $this->middleware('admin');
    }

}
```

**Comment by mehrdd** [comment]
+1

**Comment by stojankukrika** [comment]
+1 THANK you very much @scangroup!
