### ISSUE TITLE
Class 'Form' not Found Fix

### ISSUE THREAD

**Issue by applecrusher** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#32]
When I tried to create a new video I got this error

[2015-02-09 21:36:39] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Form' not found' in /vagrant/storage/framework/views/7e7bca03a0933f6594af0fb59a7f9839:61
Stack trace:
#0 /vagrant/storage/framework/compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  

To fix this I needed to add the following to the config/app.php file

Added this service provider:
'Illuminate\Html\HtmlServiceProvider'

Registered these two facades

'Form'=> 'Illuminate\Html\FormFacade',
'HTML'=> 'Illuminate\Html\HtmlFacade',

**Comment by stojankukrika** [comment]
Thank you very much for test and show me where is error, and special thanks for show me how to fix it. :+1:

**Comment by tesis** [comment]
Thank you very much, it was really helpful
