### ISSUE TITLE
Youtube Link with Video Submission Issue, with potential solution.

### ISSUE THREAD

**Issue by applecrusher** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#34]
Line 71 and Line 72 of the Admin/VideoController.php is 
$youtube = explode('http://www.youtube.com/watch?v=', $request->youtube);
$video->youtube = rtrim($youtube[1]);

However this won't work with https request so you might want to put it as just https
$youtube = explode('https://www.youtube.com/watch?v=', $request->youtube);

I don't know if youtube has just plain http request anymore so you might be Ok with just https, but that's a lot more work if you want to keep both. Also because of this there are probably other areas in the code that need to be modified. But I think http will redirect to https so everything should be ok for now.

**Comment by stojankukrika** [comment]
thanks for issue :+1: now its fixed ;)
