### ISSUE TITLE
cannot access admin panel

### ISSUE THREAD

**Issue by kbhatt2006** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#35]
after login as admin, page gets routed to home and not to the admin panel !
can you please fix this issue

**Comment by stojankukrika** [comment]
now it redirect to admin, if admin is login.

**Comment by kbhatt2006** [comment]
Did you push this commit to your demo website ! because that is still broken.

**Comment by stojankukrika** [comment]
No, I do not push last version to demo site.
