### ISSUE TITLE
readme.md: Requirements could not be resolved with composer

### ISSUE THREAD

**Issue by dandgelb** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#36]
Please note: Below problem is not present with git clone from the latest code.

While doing 'composer install --dev' as suggested in step 1(downloading master.zip) of readme.md. I am seeing following problem with the dependencies. 
You are using the deprecated option "dev". Dev packages are installed by default now.
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for greggilbert/recaptcha dev-master -> satisfiable by greggilbert/recaptcha[dev-master].
    - don't install illuminate/support v5.0.0|don't install laravel/framework 4.2.x-dev
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.0
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.0-BETA1
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.1
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.10
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.11
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.12
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.13
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.14
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.15
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.16
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.2
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.3
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.4
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.5
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.6
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.7
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.8
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.9
    - greggilbert/recaptcha dev-master requires illuminate/support 5.0.* -> satisfiable by illuminate/support[5.0.x-dev, v5.0.0].
    - Conclusion: don't install illuminate/support 5.0.x-dev
    - Installation request for laravel/framework 4.2.* -> satisfiable by laravel/framework[4.2.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.13, v4.2.14, v4.2.15, v4.2.16, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].

**Comment by stojankukrika** [comment]
Sorry, but I think that you make a mistake, I did not include or require greggilbert/recaptcha package in this start site. But it's Ok to fixes in readme to delete --dev param.
