### ISSUE TITLE
Video Album Delete Not Displaying View Fix

### ISSUE THREAD

**Issue by applecrusher** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#37]
The video album view for delete, delete.blade.php, has the variable "photoalbum" instead of "videoalbum". You can just replace the delete.blade.php for the photo album with the code below or do a replace all.

        <ul class="nav nav-tabs">
            <li class="active"><a href="#tab-general" data-toggle="tab">{{ Lang::get("admin/modal.general") }}</a></li>
        </ul>
    <form id="deleteForm" class="form-horizontal" method="post" action="@if (isset($videoalbum)){{ URL::to('admin/videoalbum/' . $videoalbum->id . '/delete') }}@endif" autocomplete="off">
        <input type="hidden" name="_token" value="{{{ csrf_token() }}}" />
        <input type="hidden" name="id" value="{{ $videoalbum->id }}" />
        <div class="form-group">
            <div class="controls">
               {{ Lang::get("admin/modal.delete_message") }}<br>
                <element class="btn btn-warning btn-sm close_popup"><span class="glyphicon glyphicon-ban-circle"></span>  {{ Lang::get("admin/modal.cancel") }}</element>
                <button type="submit" class="btn btn-sm btn-danger"><span class="glyphicon glyphicon-trash"></span> {{ Lang::get("admin/modal.delete") }}</button>
            </div>
        </div>
    </form>
@stop

**Comment by stojankukrika** [comment]
I will fixed in nex commit. TNX
