### ISSUE TITLE
Issue in Albums and sliders

### ISSUE THREAD

**Issue by kumarramalingam** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#39]
Upload photos in albums and select sliders and album cover and go to front end display the errors

QueryException in Connection.php line 615: SQLSTATE[HY000]: 

General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. (SQL: select `photo_album`.`id`, `photo_album`.`name`, `photo_album`.`description`, `photo_album`.`folderid`, (select filename from photo WHERE album_cover=1 and photo.photo_album_id=photo_album.id) AS album_image, (select filename from photo WHERE photo.photo_album_id=photo_album.id ORDER BY position ASC, id ASC LIMIT 1) AS album_image_first from `photo_album` limit 8).

**Comment by stojankukrika** [comment]
I hope that now is fix it
