### ISSUE TITLE
Hey this is an awesome app

### ISSUE THREAD

**Issue by douxlagithub** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#40]
I just got a smart app from laravel 5 powered, But after I installed, then got into admin page, I still couldn't edit all of the components. For example  I want to edit news category or even add a new category, the app returns an error page inside the popup bootstrap window. How can I get it work? Help please. All news shipped with the app already been installed through db:seed command. When I was in front page, everything was going well.

**Comment by zei** [comment]
Some if statements seem to be somewhat misformatted. If you remove the line break in lines 66-67 of views/admin/newscategory/create_edit.blade.php between the @if tag and condition, it should work.

**Comment by douxlagithub** [comment]
Oh yeah, that fixes my problem. I tried to open up all of template files then found everything was broken lines. For example the wildcard statements was broken into two lines like: 
{{ <break>
Lang::()  }}
And so and so... 
then also 
@if <break>
(some_arguments)
@endif
And more... 
It seems like the content was text-wrapped before it uploaded to the server.. 
If so, please re-upload unwrapped version if available!

**Comment by stojankukrika** [comment]
Thanks for add issue. I use Zend Studio formatter, but now I realized tat he is not the best, and user must fix it manualy. Tnx for comment. :+1:  Have a nice day.
