### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by shanka12** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#41]
Hi
When I click on "New" or Edit button, I am getting following error.
"Whoops, looks like something went wrong."
Please  help me to fix this error.

**Comment by cklam** [comment]
Just change your webroot permission to writable

**Comment by shanka12** [comment]
Thank you cklam for your reply. Could you please tell me how do I change permission in localhost?

**Comment by shanka12** [comment]
I am using wamp server in windows

**Comment by stojankukrika** [comment]
try in .env file put 
APP_DEBUG=true
and tray again to laravel show you an error. But before that, get new version of this project.

**Comment by shanka12** [comment]
Thank you stojankukrika . I got new version. its fixed now.
Thanks a lot.

**Comment by stojankukrika** [comment]
It was my pleasure :+1:
