### ISSUE TITLE
User and Role management.

### ISSUE THREAD

**Issue by intrepidtr** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#43]
User and Role management. does not work

**Comment by nextpulse** [comment]
Doesn't look like the role/permission code is written/hooked in.
(Apart from adding/deleting it from the database)

**Comment by stojankukrika** [comment]
Yea, it's not finished, because it depends on project and this is a start site. It only check if user is admin or not, did he can go to admin page or not.
