### ISSUE TITLE
General items/issues

### ISSUE THREAD

**Issue by nextpulse** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#49]
A few things I've noticed:

i) Embedded views in controller. 
This is debatable - but since this is a starter site, I'll bring it up. 
Probably not a good practice to use Datatables - as view information are now in the controller.
For example, in Admin/VideoController: public function data($albumid=0), the json is returning html render info. Best practice is to move this out and return just data.

ii) Seems there are some encoded EOL issues in the blade source files. So on execution, these views will not render. You can see the error in the laravel logs.
For example, in  video/create_edit_blade.php, around <span class="glyphicon glyphicon-ok-circle"></span>. The @if (isset($video)) has platform embedded EOL. A quick fix is to re-edit the file.

**Comment by stojankukrika** [comment]
TNX :+1:  but it is a star site, so if you did not like, you can fix it as you like :) or help me to fix it here with pull request, I would be appreciative if you can help me.
