### ISSUE TITLE
QueryException in Connection.php line 614

### ISSUE THREAD

**Issue by cklam** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#51]
QueryException in Connection.php line 614:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '{tbpfx}filename from photo WHERE album_cover=1 and ${tbpfx}photo.photo_album_id=' at line 1 (SQL: select `photo_album`.`id`, `photo_album`.`name`, `photo_album`.`description`, `photo_album`.`folderid`, (select ${tbpfx}filename from photo WHERE album_cover=1 and ${tbpfx}photo.photo_album_id=${tbpfx}photo_album.id) AS album_image, (select ${tbpfx}filename from photo WHERE ${tbpfx}photo.photo_album_id=${tbpfx}photo_album.id ORDER BY position ASC, id ASC LIMIT 1) AS album_image_first from `photo_album` limit 8)

**Comment by petrosit** [comment]
Have the same issue.

**Comment by stojankukrika** [comment]
When did you get download this star site? I fix it last night in last commit.

**Comment by JuryYavkin** [comment]
Today. What's the matter?

**Comment by petrosit** [comment]
I downloaded the master.zip today.

**Comment by pellempus** [comment]
I just downloaded. Same problem

QueryException in Connection.php line 614:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{tbpfx}filename from photo WHERE album_cover=1 and ${tbpfx}photo.photo_album_id=' at line 1 (SQL: select `photo_album`.`id`, `photo_album`.`name`, `photo_album`.`description`, `photo_album`.`folderid`, (select ${tbpfx}filename from photo WHERE album_cover=1 and ${tbpfx}photo.photo_album_id=${tbpfx}photo_album.id) AS album_image, (select ${tbpfx}filename from photo WHERE ${tbpfx}photo.photo_album_id=${tbpfx}photo_album.id ORDER BY position ASC, id ASC LIMIT 1) AS album_image_first from `photo_album` limit 8)

**Comment by pellempus** [comment]
For a temporary fix make this change in HomeController.php

public function index()
	{
        $news = $this->news->orderBy('position', 'DESC')->orderBy('created_at', 'DESC')->limit(4)->get();
        $sliders = Photo::join('photo_album', 'photo_album.id','=','photo.photo_album_id')
                        ->where('photo.slider',1)
                        ->orderBy('photo.position', 'DESC')
                        ->orderBy('photo.created_at', 'DESC')
                        ->select('photo.filename','photo.name','photo.description','photo_album.folderid')->get();

        $photoalbums = PhotoAlbum::select(array('photo_album.id', 'photo_album.name', 'photo_album.description',
                'photo_album.folderid',
                DB::raw('(select filename from photo WHERE album_cover=1 and photo.photo_album_id=photo_album.id) AS album_image'),
                DB::raw('(select filename from photo WHERE photo.photo_album_id=photo_album.id ORDER BY position ASC, id ASC LIMIT 1) AS album_image_first')))->limit(8)->get();

        $videoalbums = VideoAlbum::select(array('video_album.id', 'video_album.name', 'video_album.description',
                'video_album.folderid',
                DB::raw('(select youtube from video as v WHERE album_cover=1 and v.video_album_id=video_album.id) AS album_image'),
                DB::raw('(select youtube from video WHERE video.video_album_id=video_album.id ORDER BY position ASC, id ASC LIMIT 1) AS album_image_first')))->limit(8)->get();

        return view('site.home.index',compact('news','sliders','videoalbums','photoalbums'));
	}

**Comment by mberizzo** [comment]
Have the same issue!

**Comment by stojankukrika** [comment]
same as #53
