### ISSUE TITLE
FormRequest validations errors not showing

### ISSUE THREAD

**Issue by ricardopaiva** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#52]
Hi,

When creating or editing a video, photo or news, validation rules are working because the record is not added, but errors aren't shown.
Do you have the same problem?

I've tried with IE, Chrome and Firefox and always had the same problem.
I've tried a few changes but without success.

**Comment by applecrusher** [comment]
The fail condition in the admin/layouts/modal.blade.php could look something like this

.fail(function(jqXHR, textStatus, errorThrown) {
						// Optionally alert the user of an error here...
						var textResponse = jqXHR.responseText;
						var alertText = "One of the following conditions is not met:\n\n";
						var jsonResponse = jQuery.parseJSON(textResponse);
						
						$.each(jsonResponse, function(n, elem) {
							alertText = alertText + elem + "\n";
						});

						alert(alertText);
					});

**Comment by stojankukrika** [comment]
TNX @applecrusher I solve it problem with modal forms. Thank you very much!
