### ISSUE TITLE
Creating a new user does not hash the password.

### ISSUE THREAD

**Issue by nextpulse** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#55]
If you create a new user via the admin panel, the password/confirmation code is not hashed.
Hence the new user cannot login.
The workaround is to edit the user again via admin.

The bug is in UserController,::postCreate().
NOTE: it should hash the password as in postEdit()

**Comment by stojankukrika** [comment]
Thank you @nextpulse . I fix it now. :+1:
