### ISSUE TITLE
Laravel 5 Version Replacement Problem!

### ISSUE THREAD

**Issue by intrepidtr** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#57]
"laravel/framework": "dev-master#700bbf22bb325a3ddd10e2fc839feb9b4958387a"
some packages cannot be installed in the above version

replace version

"laravel/framework": "5.0.*@dev"

Script php artisan clear-compiled handling the post-update-cmd event returned with an error

**Comment by stojankukrika** [comment]
It's replaced 19 days ago.

**Comment by intrepidtr** [comment]
I'm sorry my project was 1 month . I'm coming to experiment
