### ISSUE TITLE
Role/permission management corrupts database

### ISSUE THREAD

**Issue by nextpulse** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#58]
I understand the role/permission code is not fully written, but what is there today can cause the tables to be corrupted.

Any attempt to add/modify the permission/roles can cause the following tables to be corrupted.
(And hence potentially causes an overall system issue)

assigned_roles
permission_roles

From first glance, it seems the relationship role_id between these tables are not correctly modified - causing the admin user to be corrupted.

IMHO: if there are no plans to develop this part - maybe it is best to just remove role/permission management (and add a simple check for is_admin). Judging from the other comments, having it there is raising the expectations.

**Comment by nextpulse** [comment]
I think this is where the bug is:
Middleware\Admin.php

           $user_roles = AssignedRoles::join('roles','assigned_roles.role_id','=','roles.id')
            ->where('user_id', $this->auth->user()->id)->select('roles.is_admin')->get();
						
Note: seems it is missing a join on the permission_role?

**Comment by kbhatt2006** [comment]
@mrakodol @stojankukrika you must look into @kodeine https://github.com/kodeine/laravel-acl if you integrate this, it would be really awesome and solve the roles/permission problem.

**Comment by stojankukrika** [comment]
TNX @kbhatt2006 maybe I will integrate it, when I find some free time to do it. 
@nextpulse   permission_roles & assigned_roles is added for Confide & Entrust because I didn't know how to laravel 5 is final look like when I start to make this project and it stay to today, but soon I will delete it, because it didn't uses.

**Comment by stojankukrika** [comment]
Now it's fixed: Delete roles because it didn't used and put admin flag into user that determine was user admin or not
