### ISSUE TITLE
On listing routes 

### ISSUE THREAD

**Issue by duard** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#59]
php artisan route:list
PHP Fatal error:  Cannot use Illuminate\Routing\Controller as BaseController because the name is already in use in /home/vagrant/Code/gomeiro/app/Http/Controllers/Controller.php on line 4

**Comment by kezkankrayon** [comment]
Pull request #65 addresses this issue.

**Comment by stojankukrika** [comment]
it fixed by @kezkankrayon
