### ISSUE TITLE
Production Host Error

### ISSUE THREAD

**Issue by pdellepiane** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#62]
Hello, I moved all the files to the production host and this is what I get:

Warning: require(/home/content/85/9398085/html/bootstrap/../vendor/autoload.php) [function.require]: failed to open stream: No such file or directory in /home/content/85/9398085/html/bootstrap/autoload.php on line 17

Fatal error: require() [function.require]: Failed opening required '/home/content/85/9398085/html/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/php5_3/lib/php') in /home/content/85/9398085/html/bootstrap/autoload.php on line 17

How do I fix it?

Thanks

**Comment by applecrusher** [comment]
Not 100% sure but why are you using PHP 5.3? You need PHP 5.4.

**Comment by pdellepiane** [comment]
Im using PHP 5.5

The thing is that I dont know what changes I need to do for production server, I have changed the .env only, is that enough?

**Comment by pdellepiane** [comment]
Im removing "vendor" from .gitignore, hope this fixes the problem, but still I think is not the right way to fix it =(, any clues?

**Comment by applecrusher** [comment]
I don't really know the answer to your first question. The reason I thought you were using 5.3 is because in your file path you have "php5_3". You might need to change the environment in the app.php file in the config folder but from what I read you should be able to do it in the .env. What does changing it in app.php do for you?

**Comment by pdellepiane** [comment]
You were right, my server was running PHP 5.3, I've changed it to 5.4, I'll let you know if that fixed the problem.

**Comment by pdellepiane** [comment]
That fixed the problem ;), Thanks! But still, im would like to know all the configurations I have to make when I move to production, anyone?

**Comment by stojankukrika** [comment]
Copy all files from local to production server, and change connection string to database in .env file. Set a host directory to start directory is public, and that's all.
