### ISSUE TITLE
.htaccess for production

### ISSUE THREAD

**Issue by pdellepiane** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#63]
Hello, I would like to know if anybody has a .htaccess for production environment.

**Comment by applecrusher** [comment]
This is what I used

# Use PHP5.4 Single php.ini as default
AddHandler application/x-httpd-php54s .php
AddType application/x-httpd-php54 .php


RewriteEngine on

RewriteCond %{HTTP_HOST} ^(www.)?mywebsite.com$ 
RewriteCond %{REQUEST_URI} !^/public/ 
RewriteCond %{REQUEST_FILENAME} !-f 
RewriteCond %{REQUEST_FILENAME} !-d 
RewriteRule ^(.*)$ /public/$1 
RewriteCond %{HTTP_HOST} ^(www.)?mywebsite.com$ 
RewriteRule ^(/)?$ public/index.php [L]

**Comment by pdellepiane** [comment]
That didnt work for me =(

**Comment by pdellepiane** [comment]
Im using godaddy =(

**Comment by stojankukrika** [comment]
I use hostgator and did not need any htaccess file. Only sett up host to default root look at public directory. But I find this 

https://medium.com/@kunalnagar/deploying-laravel-5-on-godaddy-shared-hosting-888ec96f64cd
