### ISSUE TITLE
Cannot use Illuminate\Routing\Controller as Controller because the name is already in use

### ISSUE THREAD

**Issue by leo4all** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#64]
artisan route:list

 [Symfony\Component\Debug\Exception\FatalErrorException]                                    
  Cannot use Illuminate\Routing\Controller as Controller because the name is already in use

**Comment by kezkankrayon** [comment]
Pull request #65 addresses this issue.

**Comment by arikin** [comment]
The Controller is not extended anymore in Laravel 5.  Meaning that the route filters need to be done by attaching the filter via a route::group to the resource.  Or even route::when.

**Comment by stojankukrika** [comment]
it fixed by @kezkankrayon
