### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::hasRole()

### ISSUE THREAD

**Issue by bernier** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#66]
Hello,
I have this error "Call to undefined method Illuminate\Database\Query\Builder::hasRole()"
From the call inside nav.blade.php

                                @if(Auth::user()->hasRole('admin'))
                                    <li>
                                        <a href="/admin/dashboard"><i class="fa fa-tachometer"></i> Dashboard</a>
                                    </li>
                                @endif

I installed "zizaco/entrust": "dev-laravel-5" and added it to my models but I still get the same error.
What do I need to do?
Thanks

**Comment by kezkankrayon** [comment]
Although there may be remnants, I believe "zizaco/entrust" was removed from this project in favour of Laravel's existing auth system.

Have you got a function like the following in your User Model?
https://github.com/mrakodol/Laravel-5-Bootstrap-3-Starter-Site/blob/master/app/User.php#L41-L52

**Comment by bernier** [comment]
Yes, I have it. I installed entrust in hope it would fix the issue but it doesn't.
The only difference is that I have this file inside /Models folder

**Comment by bernier** [comment]
Fixed.
I had inform model namespace in config/auth.php
I also searched for "App\User" in my entire site and replaced it by "App\Models\User"
I think it's cleaner to have a Models directory than having all the files inside app.
