### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by haovn577** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#67]
Hi, 
I have installed step by step, but when i run the last cmd (php artisan db:seed), it shows: 
Seeded: UsersTableSeeder
Seeded: RolesTableSeeder
Seeded: PermissionsTableSeeder
Seeded: LanguagesTableSeeder
Seeded: NewsCategoryTableSeeder
Seeded: NewsTableSeeder
Seeded: PhotoAlbumsTableSeeder

  [InvalidArgumentException]
  Cannot write to directory "E:\Tools\WebTools\xampp\htdocs\laravel5news\publ
  ic/image_library"

And when i open web browser to check, appear bellow errs:
file_get_contents(E:\Tools\WebTools\xampp\htdocs\laravel5news\public/build/rev-manifest.json): failed to open stream: No such file or directory (View: E:\Tools\WebTools\xampp\htdocs\laravel5news\resources\views\app.blade.php) (View: E:\Tools\WebTools\xampp\htdocs\laravel5news\resources\views\app.blade.php)

pls kind to check,
Thanks and Best Regards,
Hao Tran

**Comment by haovn577** [comment]
Hi,

I have added "image_Ở tlibrary" to "public" folder, have no above err.
But new errs below:

Seeded: UsersTableSeeder
Seeded: RolesTableSeeder
Seeded: PermissionsTableSeeder

  [Illuminate\Database\QueryException]
  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or upda
  te a parent row: a foreign key constraint fails (`laravel5news`.`news_categ
  ory`, CONSTRAINT `news_category_language_id_foreign` FOREIGN KEY (`language
  _id`) REFERENCES `language` (`id`)) (SQL: delete from `language`)

  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or upda
  te a parent row: a foreign key constraint fails (`laravel5news`.`news_categ
  ory`, CONSTRAINT `news_category_language_id_foreign` FOREIGN KEY (`language
  _id`) REFERENCES `language` (`id`))


Thanks and Best Regards,
Hao Tran

**Comment by stojankukrika** [comment]
I didn't test last merges but soon I will and fix it.

**Comment by dany-eudes** [comment]
Same here. Create the `public/image_library` folder and it will be Ok.

@haovn577, to run `php artisan db:seed` again, do a `migrate:reset` just before that: 
``php artisan migrate:reset``
``php artisan migrate``

and so run...
``php artisan db:seed``

That's it! :)

**Comment by stojankukrika** [comment]
TNX  @dany-eudes for replay
