### ISSUE TITLE
Why not use core Bootstrap elements?

### ISSUE THREAD

**Issue by VickG** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#69]
Great work on this gentlemen, but why are you not sticking to core default bootstrap elements and styling?

I also noticed the the styling and the dialog/modal windows are not of bootstrap. This starterkit is already using bootstrap and bootstrap has it's own modal view, why not use that?

**Comment by stojankukrika** [comment]
TNX. I start to make it before know boostrap and it stay in project.But I hope that find some free time to fix it, but for now it works like that, you can fix it in your projects, it's just start project to learn laravel.
