### ISSUE TITLE
Explorer TokenMismatchException 

### ISSUE THREAD

**Issue by intrepidtr** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#72]
hi,
Chrome,Firefox Login No Error;

Explorer Login error !
TokenMismatchException in VerifyCsrfToken.php line 46:

**Comment by phpclub** [comment]
Maybe need clear cookie in IE? 
My Ie work fine.

**Comment by stojankukrika** [comment]
Me to. So maybe you wait some time to submit form. Token is expire in some time.

**Comment by intrepidtr** [comment]
Thanks for your help.
did not remove the problem in a different computer
