### ISSUE TITLE
Error -  php artisan db:seed -> /public/appfiles/photoAlbum

### ISSUE THREAD

**Issue by phpclub** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#73]
Fresh instalation 
#php artisan db:seed
 [InvalidArgumentException]                                                   
  Cannot write to directory "/public/appfiles/photoAlbum"
  Cannot write to directory "/public/appfiles/videoAlbum"

**Comment by nicolascrop** [comment]
Hi,

Got the same problem

**Comment by jarnix** [comment]
Fix the folders in /tests/factories/factory.php

line 43:
'filename' => $faker->image($dir = public_path().'/appfiles/photoAlbum', $width = 320, $height = 240),

and line 64:

 'filename' => $faker->image($dir = public_path().'/appfiles/videoAlbum', $width = 320, $height = 240),

**Comment by nicolascrop** [comment]
Oki thanks, and for the problem with the gulp file its due to the bowerPath, it's /bower_components on my comp and you had ./vendor/bower_components

**Comment by kezkankrayon** [comment]
As of #76 the bowerPath was changed to, resources/vendor.
