### ISSUE TITLE
gulp

### ISSUE THREAD

**Issue by nicolascrop** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#74]
Hey,

Your gulp file doesnt create all.js and all.css any idea why? (never used it)

**Comment by kezkankrayon** [comment]
I suspect gulp is tripping on a missing resource. After running "npm install" and "bower install" do you have something like the following in your project directory?

node_modules/
├── gulp
├── gulp-notify
├── laravel-elixir
└── notify-send

vendor/bower_components/
├── bootstrap
├── bootstrap-sass
├── bootstrap-sass-official
├── bootswatch-sass
├── datatables
├── datatables-bootstrap3-plugin
├── font-awesome
├── jquery
├── jquery-colorbox
├── jquery-legacy
└── metisMenu

**Comment by nicolascrop** [comment]
Yep i have the same. I made it running by copying manually js and css files in ressources/css|js directory. I'm not a fan of elixir after that :) 1hour to make the asses running :)

**Comment by alejandri** [comment]
How i can set manually the CSS an JS files in site default layout? Any idea please
