### ISSUE TITLE
Your demo is not work after login as admin@admin.com

### ISSUE THREAD

**Issue by thinh2010** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#79]
Hello, 

I tried test your demo and I saw when I login by admin@admin.com, I got an error on every pages.

**Comment by kumarramalingam** [comment]
Hello, thinh2010

got same error but goto admin dashboard :

http://localhost/ {your_site_name } /public/index.php/admin/dashboard

Thanks!

**Comment by thinh2010** [comment]
Hello kumarramalingam,

I just want to look how the demo work :), didn't setup on my local

But anyway, thanks for your response!

**Comment by VaD3tr3M** [comment]
He didn't configure the database on the demo site, you'll have to configure your db on your site.

**Comment by stojankukrika** [comment]
Today I will post a new version of code to demo site and login will correct.
