### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by moiz2050** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#84]
when i am running this command
``composer install``
and at a certain point i am getting this 
``[Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING)
Script php artisan clear-compiled handling the post-install-cmd event returned with an error
  [RuntimeException]
  Error Output:
``
when i am continuing the next steps, on 
``php artisian migrate``
i am again getting the above error.. and unable to migrate .
plz help

**Comment by kezkankrayon** [comment]
What version of PHP are you running? You can find out by executing `php -v`. The artisan command will throw that error if you are running PHP < =5.4.

**Comment by moiz2050** [comment]
i am running 5.4.19, how ever i have figured out the issue,
take a look at my comment on this commit,

https://github.com/mrakodol/Laravel-5-Bootstrap-3-Starter-Site/commit/dd5e186308db72e3a1128a66ec4e8605ec01028e

i think you should update readme.md to php >= 5.5

**Comment by stojankukrika** [comment]
Now it's changed to >=5.5
