### ISSUE TITLE
php artisan  migrate problem

### ISSUE THREAD

**Issue by liqi77** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#85]
[Illuminate\Database\QueryException]
 SQLSTATE[HY000]: General error: 1005 Can't create table 'starter.#sql-818_2
 ' (errno: 150) (SQL: alter table `languages` add constraint languages_user_
 id_foreign foreign key (`user_id`) references `users` (`id`) on delete set
 null)

 [PDOException]
 SQLSTATE[HY000]: General error: 1005 Can't create table 'starter.#sql-818_2
 ' (errno: 150)

**Comment by liqi77** [comment]
table users must set engine innodb

**Comment by stojankukrika** [comment]
I hope that @kezkankrayon solve that problem with last migration changes
