### ISSUE TITLE
Request for Stable Release Version

### ISSUE THREAD

**Issue by applecrusher** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#87]
There has been great progress on this project and we all have mrakodol to thank for that. :+1: 

So with that in mind, would it be possible to tag a stable release that works, that way when someone wants to use this they have a version that is not being modified? It could be a beta 2 or an actually release. Thanks again!!!

**Comment by stojankukrika** [comment]
You are right @applecrusher I think tat now is time to release a version ;) THX :+1:

**Comment by applecrusher** [comment]
Thank you Stojan Kukrika!
