### ISSUE TITLE
user roles

### ISSUE THREAD

**Issue by b00yan** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#97]
i dont see any user roles in code?

**Comment by stojankukrika** [comment]
Only user and admin is roles. Is user admin, set the is_admin flag in database in users table, otherwise user is only user.

**Comment by wexford0709** [comment]
why?

**Comment by stojankukrika** [comment]
why not? :) it's not a cms it's start site :)

**Comment by b00yan** [comment]
yes but delete it from readme that it has user roles then
