### ISSUE TITLE
New Article not sending picture field

### ISSUE THREAD

**Issue by alejandri** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#98]
In condition controller 

        $picture = "";
        if(Input::hasFile('picture'))
        {
            $file = Input::file('picture');
            $filename = $file->getClientOriginalName();
            $extension = $file -> getClientOriginalExtension();
            $picture = sha1($filename . time()) . '.' . $extension;
            /// to control temp
            $picture = "aaaaa";
        }
        $news -> picture = $picture;
        $news -> save();

Nothing save to column picture, y try assign value static value ""aaaaa but condition never acces and nothing save in the row

Y try too changing argument condition to $request->picture

**Comment by stojankukrika** [comment]
yea, it's still there from first version wen I think that article have a picture, but it's changed that article now do not have option to add picture in view and code still check if there any picture to add into article.

**Comment by alejandri** [comment]
Ok thanks. I solved with 

 $.ajax({
                type : form.attr('method'),
                url : form.attr('action'),
                data : new FormData(this),
                contentType: false,       
                    cache: false,             
                    processData:false
                }).complete(function() {
                    // Optionally alert the user of success here...
                    setTimeout(function() 
                        {
                            parent.$.colorbox.close();
                            window.parent.location.reload();
                        }, 10);

                }).fail(function(jqXHR, textStatus, errorThrown) {
                                    ....... add error status right here

In other issue comments.
